import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
import {measureLoudness,loudnessGainDb,LOUDNESS_TARGET_LUFS} from '../web/reel-tools.js';
function load(supported=()=>true,globals={}){const context=vm.createContext({MediaRecorder:{isTypeSupported:supported},...globals});vm.runInContext(readFileSync(new URL('../web/finishing.js',import.meta.url),'utf8')+'\nglobalThis.finishing=SiaFinishing;',context);return context.finishing;}
const plan=[{type:'teaching-card',start:2,end:4,text:'Could you repeat that?',visual:'Polite clarification',purpose:'Teach clarification',shot:'Full frame',transition:'Soft blend',voiceover:'Continuous Sia',captionTreatment:'Keep captions',returnToSia:'Soft blend'},{type:'teaching-card',start:8,end:10,text:'Thank you for your time.',visual:'Confident close',purpose:'Teach a close',shot:'Full frame',transition:'Soft blend',voiceover:'Continuous Sia',captionTreatment:'Keep captions',returnToSia:'Soft blend'}];
test('export refuses generic MP4 and WebM without an explicit H264/AAC encoder',()=>{assert.equal(load(t=>t==='video/mp4'||t.includes('webm')).supportedMime(),null);assert.match(load().supportedMime(),/^video\/mp4;codecs=avc1[^,]*,mp4a\.40\.2$/);});
test('inserts are optional, bounded, nonoverlapping, and Sia stays the majority',()=>{const f=load();assert.equal(f.validateBroll(plan,20).length,2);assert.equal(f.validateBroll([],20).length,0);assert.equal(f.validateBroll([plan[0]],20).length,1);assert.equal(f.validateBroll([{type:'text-overlay',mark:'wrong',text:'Myself Riya?',start:1,end:4.5}],20).length,1);for(const [p,d] of [[[plan[0],plan[1],plan[0],plan[1]],40],[[{type:'text-overlay',text:'x',start:1,end:6}],20],[[{...plan[0],end:6},plan[1]],20],[[plan[0],{...plan[1],start:3,end:5}],20],[plan,7],[[plan[0],{...plan[1],type:'stock'}],20],[plan,8]])assert.throws(()=>f.validateBroll(p,d));});
test('captions reject more than eight words and preserve source casing',()=>{const f=load();assert.throws(()=>f.validateCaptions([{start:0,end:2,text:'one two three four five six seven eight nine'}],3),/eight/i);const c=[{start:0,end:2,text:'Could you repeat that?'}];assert.equal(f.validateCaptions(c,3)[0].text,c[0].text);});
test('retention zoom is subtle, deterministic and changes every three seconds',()=>{const f=load();assert.equal(f.retentionZoom(0),1);assert.ok(f.retentionZoom(3.4)>1);assert.equal(f.retentionZoom(3.4),f.retentionZoom(3.4));assert.equal(f.retentionZoom(6.4),1);assert.ok(f.retentionZoom(4)<=1.045);});
function drawingContext(){const calls=[];return {canvas:{width:1080,height:1920},calls,globalAlpha:1,save(){},restore(){},translate(){},scale(){},strokeText(text){calls.push(['stroke',text,this.strokeStyle]);},roundRect(){calls.push(['round',this.fillStyle]);},fillRect(...args){calls.push(['rect',...args]);},drawImage(...args){calls.push(['image',...args]);},fillText(text,...args){calls.push(['text',text,this.fillStyle,...args]);},measureText(text){return {width:text.length*27};},createLinearGradient(){return {addColorStop(){}};},beginPath(){},fill(){},stroke(){},moveTo(){},lineTo(){},arc(){}};}
test('cover fills portrait without bars even if obsolete contain is requested',()=>{const f=load(),ctx=drawingContext();f.draw(ctx,{videoWidth:1920,videoHeight:1080},0,{fit:'contain'},[],null,[],[]);const [,v,sx,sy,sw,sh,x,y,w,h]=ctx.calls.find(c=>c[0]==='image');assert.ok(w>=1080&&h>=1920);assert.ok(x<=0&&y<=0);assert.equal(sx,0);assert.equal(sy,0);assert.equal(sw,1920);assert.equal(sh,1080);});
test('teaching card blends over Sia while exact captions stay visible; the spoken word gets the orange pill and teaching terms are gold',()=>{const f=load(),ctx=drawingContext();f.draw(ctx,{videoWidth:1080,videoHeight:1920},3,{},[{start:0,end:5,text:'Could you repeat that?'}],null,plan,['repeat']);const text=ctx.calls.filter(c=>c[0]==='text');assert.ok(text.some(c=>c[1]==='repeat'&&c[2]==='#FFFFFF'));assert.ok(ctx.calls.some(c=>c[0]==='round'&&c[1]==='#FF4D00'));const early=drawingContext();f.draw(early,{videoWidth:1080,videoHeight:1920},.5,{},[{start:0,end:5,text:'Could you repeat that?'}],null,[],['repeat']);assert.ok(early.calls.some(c=>c[0]==='text'&&c[1]==='repeat'&&c[2]==='#FFB61E'));assert.ok(early.calls.some(c=>c[0]==='stroke'&&c[1]==='repeat'&&c[2]==='#191D23'));assert.ok(text.some(c=>c[1]==='Could'));assert.ok(text.some(c=>c[1]==='that?'));assert.ok(text.some(c=>c[1].includes('Could you repeat')));});
test('audio graph applies the loudness gain and explicitly upmixes mono to two discrete recorder channels',()=>{const connections=[],nodes=[];let gains=0;const node=kind=>{const n={kind,gain:{value:1},connect(...to){connections.push([kind,...to]);}};nodes.push(n);return n;};const context={createMediaElementSource:()=>node('source'),createGain:()=>node(gains++?'mono':'loudness'),createChannelMerger:n=>{assert.equal(n,2);return node('stereo');},createAnalyser:()=>node('analyser'),createMediaStreamDestination:()=>node('destination')};const {destination,loudness}=load().stereoAudioGraph(context,{},-6);assert.ok(Math.abs(loudness.gain.value-10**(-6/20))<1e-9);assert.deepEqual(connections.filter(c=>c[0]==='source').map(c=>c[1].kind),['loudness']);assert.deepEqual(connections.filter(c=>c[0]==='loudness').map(c=>c[1].kind),['mono']);assert.equal(nodes.find(n=>n.kind==='mono').channelCount,1);assert.equal(destination.channelCount,2);assert.equal(destination.channelCountMode,'explicit');const mono=connections.filter(c=>c[0]==='mono');assert.deepEqual(mono.map(c=>c.slice(2)),[[0,0],[0,1]]);});
test('oversized unbroken caption text fails instead of leaving the safe area',()=>{const f=load(),ctx=drawingContext();assert.throws(()=>f.draw(ctx,{videoWidth:1080,videoHeight:1920},1,{},[{start:0,end:2,text:'x'.repeat(80)}],null),/long/);});
test('render requests 60 FPS capture headroom without claiming actual encoded FPS',async()=>{
 const captured=[],track={stop(){}},canvas={getContext:()=>({}),captureStream(fps){captured.push(fps);return {getVideoTracks:()=>[track]};}};
 const media=tag=>{const events={};return {duration:20,videoWidth:1080,videoHeight:1920,addEventListener(name,fn){events[name]=fn;},removeEventListener(name){delete events[name];},load(){events[tag==='audio'?'canplay':'loadeddata']?.();},pause(){},removeAttribute(){}};};
 const node=()=>({connect(){},gain:{value:1},stream:{getAudioTracks:()=>[track]}});
 const tone=new Float32Array(48000);for(let i=0;i<tone.length;i++)tone[i]=.3*Math.sin(i/7);
 class AudioContext{decodeAudioData(){return Promise.resolve({sampleRate:48000,getChannelData:()=>tone});}resume(){return Promise.resolve();}close(){return Promise.resolve();}createMediaElementSource(){return node();}createGain(){return node();}createChannelMerger(){return node();}createAnalyser(){return node();}createMediaStreamDestination(){return node();}}
 const stop=Error('Stop after recorder setup');class MediaRecorder{static isTypeSupported(){return true;}constructor(){throw stop;}}
 const f=load(undefined,{MediaRecorder,window:{ReelTools:{toSrt(){},LOUDNESS_TARGET_LUFS,measureLoudness,loudnessGainDb},AudioContext},document:{hidden:false,createElement:tag=>tag==='canvas'?canvas:media(tag),removeEventListener(){}},fetch:async()=>({ok:true,blob:async()=>({arrayBuffer:async()=>new ArrayBuffer(8)})}),URL:{createObjectURL:()=>'/local-test-media',revokeObjectURL(){}},MediaStream:class{constructor(tracks){this.tracks=tracks;}getTracks(){return this.tracks;}},setTimeout,clearTimeout,performance,cancelAnimationFrame(){}});
 await assert.rejects(f.render({job:{body:{audioDuration:20,mediaKey:'source',audioKey:'voice',production:{broll:plan,highlightTerms:['repeat']}}},captions:[{start:0,end:20,text:'Could you repeat that?'}],settings:{logo:false}}),error=>error===stop);
 assert.deepEqual(captured,[60]);
});
test('startup launches both clocks without waiting for video and aligns to original audio',async()=>{
 const calls=[];let release;const video={currentTime:.8,play(){calls.push('video');return new Promise(resolve=>{release=resolve;});}},audio={currentTime:.1,play(){calls.push('audio');return Promise.resolve();}};
 const started=load().startPlayback(video,audio);assert.deepEqual(calls,['video','audio']);release();const diagnostic=await started;assert.equal(video.currentTime,.1);assert.equal(audio.currentTime,.1);assert.ok(diagnostic.initialDrift>.6);
});
test('playback synchronization corrects initial offset and respects seek cooldown',()=>{
 const f=load(),state={};let d=f.playbackSyncDecision(state,{now:0,expected:.4,videoTime:.85,readyState:4,seeking:false,paused:false});assert.equal(d.action,'seek');assert.equal(d.target,.4);
 d=f.playbackSyncDecision(state,{now:.2,expected:.6,videoTime:.9,readyState:4,seeking:false,paused:false});assert.equal(d.action,'none');
 d=f.playbackSyncDecision(state,{now:.4,expected:.8,videoTime:.81,readyState:4,seeking:false,paused:false});assert.equal(d.action,'none');assert.equal(state.badSince,null);
});
test('persistent decoder starvation fails with actual clock diagnostics',()=>{
 const f=load(),state={};const sample={expected:3.2,videoTime:1.1,readyState:1,seeking:false,paused:false};assert.equal(f.playbackSyncDecision(state,{...sample,now:0}).action,'none');const d=f.playbackSyncDecision(state,{...sample,now:2.1});assert.equal(d.action,'fail');assert.match(d.message,/voice=3.200s/);assert.match(d.message,/video=1.100s/);assert.match(d.message,/readyState=1/);
});
test('repeated drift cannot be hidden by an endless stream of correction seeks',()=>{
 const f=load(),state={};let result;for(let i=0;i<6;i++){result=f.playbackSyncDecision(state,{now:i,expected:i+.5,videoTime:i,readyState:4,seeking:false,paused:false});if(result.action==='fail')break;f.playbackSyncDecision(state,{now:i+.2,expected:i+.7,videoTime:i+.7,readyState:4,seeking:false,paused:false});}assert.equal(result.action,'fail');assert.match(result.message,/corrections=/);
});

test('bottom source crop excludes lower shirt before cover framing without stretching',()=>{const ctx=drawingContext();load().draw(ctx,{videoWidth:1280,videoHeight:720},0,{cropBottom:.25},[],null);const [,video,sx,sy,sw,sh,x,y,dw,dh]=ctx.calls.find(c=>c[0]==='image');assert.deepEqual([sx,sy,sw,sh],[0,0,1280,540]);assert.ok(Math.abs(dw/sw-dh/sh)<1e-12);assert.ok(dw>=1080&&dh>=1920);assert.equal(x,(1080-dw)/2);assert.equal(y,0);});
test('source crop stays within zero to 35 percent',()=>{for(const [requested,expected]of [[-.1,720],[.9,468],[undefined,720]]){const ctx=drawingContext();load().draw(ctx,{videoWidth:1280,videoHeight:720},0,{cropBottom:requested},[],null);assert.equal(ctx.calls.find(c=>c[0]==='image')[5],expected);}});

test('text overlay keeps Sia visible: video is drawn, the card sits over her, wrong lines get a red mark and strike',()=>{const f=load(),ctx=drawingContext();const overlay={type:'text-overlay',mark:'wrong',text:'Myself Riya?',start:1,end:3.2};f.draw(ctx,{videoWidth:1080,videoHeight:1920},2,{},[],null,[overlay],[]);
 const imageAt=ctx.calls.findIndex(c=>c[0]==='image');assert.ok(imageAt>=0);assert.ok(!ctx.calls.slice(imageAt+1).some(c=>c[0]==='rect'),'no full-screen fill after Sia');assert.ok(ctx.calls.some(c=>c[0]==='text'&&c[1]==='Myself Riya?'&&c[2]==='#191D23'));assert.equal(f.BRAND.red,'#D83C3C');assert.equal(f.BRAND.font.split(',')[0],'Figtree');});
test('karaoke word timing uses real voice timestamps when they match the cue',()=>{const f=load();const cue={start:1,end:2,text:'Good morning.'};assert.deepEqual([...f.cueWordTimes(cue,[{word:'Good',start:1,end:1.3},{word:'morning.',start:1.4,end:1.9}])],[1,1.4]);assert.deepEqual([...f.cueWordTimes(cue,[])],[1,1.5]);});
