import test from 'node:test';import assert from 'node:assert/strict';import {defaultProduction,validateProduction,alignCaptionWords,validateCaptionTranscript,toSrt,wordCaptionCues,measureLoudness,loudnessGainDb,scriptConsistency,resolveBrollTiming} from '../web/reel-tools.js';
const v={id:'script-v5',body:{versionNumber:5,name:'Pilot',script:'My name is Riya. I am a student.',duration:30,language:'Hinglish',scenes:[],prompt:'Only Sia.'}};
test('production preserves exact selected script and rejects stale prompt/format',()=>{const p=defaultProduction(v);assert.deepEqual(validateProduction(v.body,p),[]);assert.ok(p.prompt.includes(v.body.script));p.prompt='old v4';p.format.width=720;assert.ok(validateProduction(v.body,p).some(e=>e.includes('exact selected full script')));assert.ok(validateProduction(v.body,p).some(e=>e.includes('width')));});
test('caption spelling follows script while retaining voice word timing',()=>{const words='My name is Riya I am a student'.split(' ').map((word,i)=>({word,start:i*.3,end:i*.3+.2}));const aligned=alignCaptionWords(v.body.script,words);assert.equal(aligned[3].word,'Riya.');assert.equal(aligned.at(-1).end,2.3000000000000003);assert.equal(validateCaptionTranscript(v.body.script,[{text:aligned.map(w=>w.word).join(' ')}]),true);assert.equal(validateCaptionTranscript(v.body.script,[{text:'Old script'}]),false);assert.match(toSrt([{start:0,end:1.25,text:'My name is Riya.'}]),/00:00:01,250/);});
test('rejects unrelated provider transcript and incomplete B-roll plans',()=>{assert.throws(()=>alignCaptionWords('a b c d e f g h i j k',[{word:'unrelated',start:0,end:1}]),/differ/);const p=defaultProduction(v);p.broll=[{type:'text-overlay',mark:'right',text:'My name is Riya.',start:1,end:6}];assert.ok(validateProduction(v.body,p).some(s=>s.includes('timing')));});

test('preflight catches plans the renderer cannot finish',()=>{const p=defaultProduction(v);p.broll=[{type:'text-overlay',mark:'',text:Array(21).fill('word').join(' '),start:1,end:3}];assert.ok(validateProduction(v.body,p).some(e=>e.includes('20 words')));p.broll=null;assert.ok(validateProduction(v.body,p).length);});
test('missing timestamp gaps fail safely instead of creating overlapping captions',()=>{assert.throws(()=>alignCaptionWords('one two three four five six seven', ['one','two','three','four','five','seven'].map((word,i)=>({word,start:i,end:i+1}))),/manual alignment/);assert.throws(()=>alignCaptionWords('one two three four',[{word:'unrelated',start:0,end:1},{word:'other',start:1,end:2}]),/differ/);});

test('Sia can stay full screen: zero inserts is valid, overlays sit over her, bad marks and models are rejected',()=>{const p=defaultProduction(v);assert.deepEqual(p.broll,[]);assert.deepEqual(validateProduction(v.body,p),[]);
 const withOverlays=defaultProduction({...v,body:{...v.body,overlays:[{text:'Myself Riya?',mark:'wrong',seconds:2.2},{text:'My name is Riya.',mark:'right',seconds:3}]}});assert.equal(withOverlays.broll.length,2);assert.ok(withOverlays.broll.every(b=>b.type==='text-overlay'));assert.deepEqual(validateProduction(v.body,withOverlays),[]);
 assert.ok(validateProduction(v.body,{...p,broll:[{type:'text-overlay',mark:'maybe',text:'x',start:1,end:2}]}).some(e=>e.includes('mark')));assert.ok(validateProduction(v.body,{...p,providerModel:'made-up/model'}).some(e=>e.includes('video model')));assert.deepEqual(validateProduction(v.body,{...p,providerModel:'kling/ai-avatar-pro'}),[]);
 assert.ok(!/calm|small natural gestures/i.test(defaultProduction({...v,body:{...v.body,prompt:''}}).presenterPrompt));});
test('overlay timing follows the spoken phrase and never overlaps',()=>{const words='Myself Riya? Yeh galti mat karna. My name is Riya.'.split(' ').map((word,i)=>({word,start:i*.5,end:i*.5+.4}));const r=resolveBrollTiming({broll:[{type:'text-overlay',text:'Myself Riya?',start:0,end:2.2},{type:'text-overlay',text:'My name is Riya.',start:0,end:2}]},words,6);assert.equal(r[0].start,0);assert.equal(r[1].start,3);assert.ok(r[1].start>=r[0].end);});
test('captions are one to three words and break after punctuation',()=>{const words="Sahi line: Good morning. I'm Riya.".split(' ').map((word,i)=>({word,start:i*.4,end:i*.4+.3}));const cues=wordCaptionCues(words);assert.deepEqual(cues.map(c=>c.text),['Sahi line:','Good morning.',"I'm Riya."]);assert.ok(cues.every(c=>c.text.split(' ').length<=3));assert.equal(validateCaptionTranscript("Sahi line: Good morning. I'm Riya.",cues),true);for(let i=1;i<cues.length;i++)assert.ok(cues[i].start>=cues[i-1].end);});
test('loudness meter matches the BS.1770 reference and targets -14 LUFS with peak headroom',()=>{const sr=48000,s=new Float32Array(sr*4);for(let i=0;i<s.length;i++)s[i]=.1*Math.sin(2*Math.PI*997*i/sr);const one=measureLoudness([s],sr),two=measureLoudness([s,s],sr);assert.ok(Math.abs(one.integrated+23.01)<.05,String(one.integrated));assert.ok(Math.abs(two.integrated+20)<.05);assert.equal(loudnessGainDb(two),6);
 assert.equal(loudnessGainDb({integrated:-10.3,peakDb:-.6}),-3.7);assert.equal(loudnessGainDb({integrated:-30,peakDb:-4}),3);assert.equal(loudnessGainDb({integrated:-Infinity,peakDb:-Infinity}),0);});
test('consistency check catches the drift found in the V5 pilot and passes a clean script',()=>{const bad={script:'Do you have an Interview? Yeh do lines. My name is Riya. Bolke dekho: My name is Rina.',hook:'Interview? Yeh do lines.',cta:'Apna introduction bolkar dekho.',duration:45,scenes:[{voiceover:'Old V1 text.'}]};const issues=scriptConsistency(bad).join(' ');for(const k of ['Scene voiceover','hook','CTA','Target is 45s','Riya, Rina'])assert.ok(issues.includes(k),k);
 const good={script:'Myself Riya? Galti. Sahi line: Good morning. Comment mein likho.',hook:'Myself Riya?',cta:'Comment mein likho.',duration:4,scenes:[{voiceover:'Myself Riya? Galti.'},{voiceover:'Sahi line: Good morning. Comment mein likho.'}]};assert.deepEqual(scriptConsistency(good),[]);});
