import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
function load(supported=()=>true){const context=vm.createContext({MediaRecorder:{isTypeSupported:supported}});vm.runInContext(readFileSync(new URL('../web/finishing.js',import.meta.url),'utf8')+'\nglobalThis.finishing=SiaFinishing;',context);return context.finishing;}
const plan=[{type:'teaching-card',start:2,end:4,text:'Could you repeat that?',visual:'Polite clarification',purpose:'Teach clarification',shot:'Full frame',transition:'Soft blend',voiceover:'Continuous Sia',captionTreatment:'Keep captions',returnToSia:'Soft blend'},{type:'teaching-card',start:8,end:10,text:'Thank you for your time.',visual:'Confident close',purpose:'Teach a close',shot:'Full frame',transition:'Soft blend',voiceover:'Continuous Sia',captionTreatment:'Keep captions',returnToSia:'Soft blend'}];
test('export refuses generic MP4 and WebM without an explicit H264/AAC encoder',()=>{assert.equal(load(t=>t==='video/mp4'||t.includes('webm')).supportedMime(),null);assert.match(load().supportedMime(),/^video\/mp4;codecs=avc1[^,]*,mp4a\.40\.2$/);});
test('B-roll requires two or three bounded nonoverlapping teaching inserts and majority Sia',()=>{const f=load();assert.equal(f.validateBroll(plan,20).length,2);for(const [p,d] of [[[],20],[[plan[0]],20],[[{...plan[0],end:6},plan[1]],20],[[plan[0],{...plan[1],start:3,end:5}],20],[plan,7],[[plan[0],{...plan[1],type:'stock'}],20],[plan,8]])assert.throws(()=>f.validateBroll(p,d));});
test('captions reject more than eight words and preserve source casing',()=>{const f=load();assert.throws(()=>f.validateCaptions([{start:0,end:2,text:'one two three four five six seven eight nine'}],3),/eight/i);const c=[{start:0,end:2,text:'Could you repeat that?'}];assert.equal(f.validateCaptions(c,3)[0].text,c[0].text);});
test('retention zoom is subtle, deterministic and changes every three seconds',()=>{const f=load();assert.equal(f.retentionZoom(0),1);assert.ok(f.retentionZoom(3.4)>1);assert.equal(f.retentionZoom(3.4),f.retentionZoom(3.4));assert.equal(f.retentionZoom(6.4),1);assert.ok(f.retentionZoom(4)<=1.045);});
function drawingContext(){const calls=[];return {canvas:{width:1080,height:1920},calls,globalAlpha:1,save(){},restore(){},fillRect(...args){calls.push(['rect',...args]);},drawImage(...args){calls.push(['image',...args]);},fillText(text,...args){calls.push(['text',text,this.fillStyle,...args]);},measureText(text){return {width:text.length*27};},createLinearGradient(){return {addColorStop(){}};},beginPath(){},roundRect(){},fill(){},stroke(){},moveTo(){},lineTo(){},arc(){}};}
test('cover fills portrait without bars even if obsolete contain is requested',()=>{const f=load(),ctx=drawingContext();f.draw(ctx,{videoWidth:1920,videoHeight:1080},0,{fit:'contain'},[],null,[],[]);const [,v,x,y,w,h]=ctx.calls.find(c=>c[0]==='image');assert.ok(w>=1080&&h>=1920);assert.ok(x<=0&&y<=0);});
test('teaching card blends over Sia while exact captions stay visible with orange highlights',()=>{const f=load(),ctx=drawingContext();f.draw(ctx,{videoWidth:1080,videoHeight:1920},3,{},[{start:0,end:5,text:'Could you repeat that?'}],null,plan,['repeat']);const text=ctx.calls.filter(c=>c[0]==='text');assert.ok(text.some(c=>c[1]==='repeat'&&c[2]==='#ff8a3d'));assert.ok(text.some(c=>c[1]==='Could'));assert.ok(text.some(c=>c[1]==='that?'));assert.ok(text.some(c=>c[1].includes('Could you repeat')));});
test('audio graph explicitly upmixes mono to two discrete recorder channels',()=>{const connections=[],nodes=[];const node=kind=>{const n={kind,connect(...to){connections.push([kind,...to]);}};nodes.push(n);return n;};const context={createMediaElementSource:()=>node('source'),createGain:()=>node('mono'),createChannelMerger:n=>{assert.equal(n,2);return node('stereo');},createAnalyser:()=>node('analyser'),createMediaStreamDestination:()=>node('destination')};const {destination}=load().stereoAudioGraph(context,{});assert.equal(nodes.find(n=>n.kind==='mono').channelCount,1);assert.equal(destination.channelCount,2);assert.equal(destination.channelCountMode,'explicit');const mono=connections.filter(c=>c[0]==='mono');assert.deepEqual(mono.map(c=>c.slice(2)),[[0,0],[0,1]]);});
test('oversized unbroken caption text fails instead of leaving the safe area',()=>{const f=load(),ctx=drawingContext();assert.throws(()=>f.draw(ctx,{videoWidth:1080,videoHeight:1920},1,{},[{start:0,end:2,text:'x'.repeat(80)}],null),/long/);});
