import {handlePhase1} from './phase1.js';
const json=(v,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}});
const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
function store(env){if(!env.DB)fail('Workspace storage is unavailable.',503);return env.DB;}
async function event(db,user,action,target){await db.prepare('INSERT INTO events (id,at,actor,action,target) VALUES (?,?,?,?,?)').bind(id(),now(),user.email,action,target).run();}
async function identity(request,env){const local=env.LOCAL_PREVIEW==='true'&&['127.0.0.1','localhost'].includes(new URL(request.url).hostname);const userId=local?'local-owner':request.headers.get('oai-authenticated-user-id');const email=local?'preview@example.test':request.headers.get('oai-authenticated-user-email')?.toLowerCase();if(!userId||!email)fail('Sign in to this private workspace to continue.',401);const db=store(env);await db.prepare("INSERT INTO members (email,user_id,role) SELECT ?,?,'Owner' WHERE NOT EXISTS (SELECT 1 FROM members)").bind(email,userId).run();const member=await db.prepare('SELECT * FROM members WHERE email=?').bind(email).first();if(!member||member.user_id&&member.user_id!==userId)fail('This account is not a workspace member.',403);if(!member.user_id)await db.prepare('UPDATE members SET user_id=? WHERE email=? AND user_id IS NULL').bind(userId,email).run();return {id:userId,email,role:member.role};}
const writeAllowed=user=>{if(!['Owner','Manager','Creator','Approver'].includes(user.role))fail('This role is read-only.',403)};
const approveAllowed=user=>{if(!['Owner','Manager','Approver'].includes(user.role))fail('An approver is required.',403)};
async function body(req,max=1500000){if(Number(req.headers.get('content-length')||0)>max)fail('Request too large.',413);const text=await req.text();if(text.length>max)fail('Request too large.',413);try{return JSON.parse(text)}catch{fail('Valid JSON is required.')}}
function textValue(v,name,max=50000){if(typeof v!=='string'||!v.trim()||v.length>max)fail('Invalid '+name);return v;}
function readiness(env){const checks=[['Kie API key',!!env.KIE_API_KEY],['Cartesia API key',!!env.CARTESIA_API_KEY],['Sia voice ID',!!env.CARTESIA_SIA_VOICE_ID],['Cartesia API version',!!env.CARTESIA_API_VERSION],['Generation enabled by owner',env.GENERATION_ENABLED==='true'],...(env.__providerVault? [['Saved connections checked',env.__providerChecked===true]]:[])];return {checks:checks.map(([name,ready])=>({name,ready})),ready:checks.every(x=>x[1]),publishing:false,mode:'Sia presenter drafts; caption finishing and human media QA required'};}
function parseRow(r){return r?{...r,body:JSON.parse(r.body),approval:r.approval?JSON.parse(r.approval):null}:null;}
async function providerJson(url,init){const r=await fetch(url,{...init,redirect:'manual',signal:AbortSignal.timeout(25000)});if(!r.ok)fail('Provider request failed (HTTP '+r.status+'). Check connection and usage in the provider dashboard.',502);const d=await r.json();if(d.code&&d.code!==200)fail('Provider did not accept the request. Check provider dashboard.',502);return d;}
function approvedProviderUrl(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port) return false;return ['file.aiquickdraw.com','tempfile.aiquickdraw.com','tempfile.redpandaai.co','kieai.redpandaai.co'].includes(u.hostname)}catch{return false}}
async function uploadKie(env,bytes,type,name){let raw='';for(let i=0;i<bytes.length;i+=16384)raw+=String.fromCharCode(...bytes.subarray(i,i+16384));const d=await providerJson('https://kieai.redpandaai.co/api/file-base64-upload',{method:'POST',headers:{Authorization:'Bearer '+env.KIE_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({base64Data:`data:${type};base64,${btoa(raw)}`,uploadPath:'speakx',fileName:name})});if(!approvedProviderUrl(d.data?.downloadUrl))fail('Provider returned an unverified asset host. Job held for review.',502);return d.data.downloadUrl;}
async function updateJob(db,j,patch){const body={...j.body,...patch.body};await db.prepare('UPDATE jobs SET status=?,stage=?,provider_id=?,body=?,updated_at=? WHERE id=?').bind(patch.status||j.status,patch.stage||j.stage,patch.providerId||j.provider_id||null,JSON.stringify(body),now(),j.id).run();return parseRow(await db.prepare('SELECT * FROM jobs WHERE id=?').bind(j.id).first());}
async function advanceJob(db,env,j){if(j.body.phase1)fail('Use the Phase 1 workspace to resume this job.',409);if(['Completed','Failed','Held'].includes(j.status))return j;if(j.status==='Processing'){if(Date.now()-Date.parse(j.updated_at)>120000)return updateJob(db,j,{status:'Held',body:{error:'The provider outcome is uncertain. Reconcile in the provider dashboard before creating another version; no automatic resubmission.'}});return j;}
if(j.stage==='poll'){const d=await providerJson('https://api.kie.ai/api/v1/jobs/recordInfo?taskId='+encodeURIComponent(j.provider_id),{headers:{Authorization:'Bearer '+env.KIE_API_KEY}});if(d.data?.state==='fail')return updateJob(db,j,{status:'Failed',body:{error:'Video provider reported failure. Review provider job before retry.'}});if(d.data?.state!=='success')return j;let urls;try{urls=JSON.parse(d.data.resultJson).resultUrls}catch{fail('Unrecognized provider result.',502)}if(!urls?.length||!approvedProviderUrl(urls[0]))return updateJob(db,j,{status:'Held',body:{error:'Result host requires verification before media can be stored.'}});const r=await fetch(urls[0],{redirect:'manual',signal:AbortSignal.timeout(25000)});if(!r.ok||!r.headers.get('content-type')?.startsWith('video/'))fail('Video result unavailable.',502);const size=Number(r.headers.get('content-length'));if(!Number.isFinite(size)||size<1||size>80*1024*1024)fail('Video size needs review.',502);const mediaKey='jobs/'+j.id+'/draft.mp4';await env.BUCKET.put(mediaKey,r.body,{httpMetadata:{contentType:'video/mp4'}});return updateJob(db,j,{status:'Completed',stage:'draft_ready',body:{mediaKey,outputKind:'Uncaptioned presenter draft; needs finishing',completedAt:now()}});}
const lock=await db.prepare("UPDATE jobs SET status='Processing',updated_at=? WHERE id=? AND status IN ('Queued','Generating') AND stage=?").bind(now(),j.id,j.stage).run();if(!lock.meta.changes)return parseRow(await db.prepare('SELECT * FROM jobs WHERE id=?').bind(j.id).first());
try{const v=parseRow(await db.prepare('SELECT * FROM versions WHERE id=?').bind(j.version_id).first());if(j.stage==='voice'){const r=await fetch('https://api.cartesia.ai/tts/bytes',{method:'POST',redirect:'manual',signal:AbortSignal.timeout(25000),headers:{Authorization:'Bearer '+env.CARTESIA_API_KEY,'Cartesia-Version':env.CARTESIA_API_VERSION,'Content-Type':'application/json'},body:JSON.stringify({model_id:env.CARTESIA_MODEL||'sonic-3.6',transcript:j.body.sceneIndex===null?v.body.script:v.body.scenes[j.body.sceneIndex].voiceover,voice:env.CARTESIA_SIA_VOICE_ID,output_format:{container:'wav',encoding:'pcm_s16le',sample_rate:44100},language:'hi',generation_config:{speed:1,volume:1}})});if(!r.ok)fail('Cartesia rejected synthesis. Check key, voice ID and API version.',502);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length>10*1024*1024||bytes.length<44)fail('Unexpected audio size.',502);const audioKey='jobs/'+j.id+'/voice.wav';await env.BUCKET.put(audioKey,bytes,{httpMetadata:{contentType:'audio/wav'}});return updateJob(db,j,{status:'Generating',stage:'upload',body:{audioKey}});}
if(j.stage==='upload'){const image=await env.BUCKET.get(v.body.referenceKey),audio=await env.BUCKET.get(j.body.audioKey);if(!image||!audio)fail('Approved image or voice is unavailable.',503);const imageUrl=await uploadKie(env,new Uint8Array(await image.arrayBuffer()),image.httpMetadata.contentType,j.id+'-sia.png');const audioUrl=await uploadKie(env,new Uint8Array(await audio.arrayBuffer()),'audio/wav',j.id+'-voice.wav');return updateJob(db,j,{status:'Generating',stage:'video',body:{imageUrl,audioUrl}});}
if(j.stage==='video'){const prompt=j.body.sceneIndex===null?v.body.prompt:v.body.scenes[j.body.sceneIndex].shot+' '+v.body.scenes[j.body.sceneIndex].edit;const d=await providerJson('https://api.kie.ai/api/v1/jobs/createTask',{method:'POST',headers:{Authorization:'Bearer '+env.KIE_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:'infinitalk/from-audio',input:{image_url:j.body.imageUrl,audio_url:j.body.audioUrl,prompt:('Only Sia, the same sole adult presenter as the approved reference. Match provided audio. No other people or voices. No generated text. '+prompt).slice(0,5000),resolution:'720p'}})});if(!d.data?.taskId)fail('Provider task ID missing; reconcile before retry.',502);return updateJob(db,j,{status:'Generating',stage:'poll',providerId:d.data.taskId});}fail('Unknown job stage.',400);}catch(e){return updateJob(db,j,{status:'Held',body:{error:e.status?e.message:'Provider outcome is uncertain. Check provider dashboard before retrying; this job will not automatically resubmit.'}});}}
const ownerOnly=user=>{if(user.role!=='Owner')fail('Only the workspace owner can manage provider connections.',403)};
const encode64=bytes=>btoa(String.fromCharCode(...bytes));
const decode64=value=>Uint8Array.from(atob(value),x=>x.charCodeAt(0));
async function vaultKey(env){try{const raw=decode64(env.PROVIDER_VAULT_KEY||'');if(raw.length!==32)throw Error();return await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}catch{fail('Secure key storage is unavailable. Contact the site owner; no credentials were saved.',503)}}
async function sealProvider(env,value){const key=await vaultKey(env),iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('speakx:provider-settings:v1')},key,new TextEncoder().encode(JSON.stringify(value)));return JSON.stringify({v:1,iv:encode64(iv),cipher:encode64(new Uint8Array(cipher))});}
async function openProvider(env,body){try{const key=await vaultKey(env),box=JSON.parse(body);if(box.v!==1)throw Error();const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode64(box.iv),additionalData:new TextEncoder().encode('speakx:provider-settings:v1')},key,decode64(box.cipher));return JSON.parse(new TextDecoder().decode(plain));}catch{fail('Saved provider settings could not be opened. Secure storage needs attention; no provider request was sent.',503)}}
async function providerState(db,env){const row=await db.prepare("SELECT * FROM provider_settings WHERE id='production'").first();return {row,value:row?await openProvider(env,row.body):{}};}
async function providerSummary(db,env){const {row,value}=await providerState(db,env);const used=Number((await db.prepare('SELECT COUNT(*) AS n FROM jobs').first()).n);return {storageReady:!!env.PROVIDER_VAULT_KEY,revision:row?.revision||0,configured:{kie:!!(value.kieKey||env.KIE_API_KEY),cartesia:!!(value.cartesiaKey||env.CARTESIA_API_KEY)},voiceId:value.voiceId||env.CARTESIA_SIA_VOICE_ID||'',apiVersion:value.apiVersion||env.CARTESIA_API_VERSION||'2026-08-14',enabled:!!row?.enabled,validation:row?JSON.parse(row.validation):{},checked:!!row&&row.checked_revision===row.revision,remainingTests:Math.max(0,1-used),updatedAt:row?.updated_at||null};}
async function providerEnvironment(db,env){const {row,value}=await providerState(db,env);if(!row)return env;const validation=JSON.parse(row.validation);return {...env,KIE_API_KEY:value.kieKey,CARTESIA_API_KEY:value.cartesiaKey,CARTESIA_SIA_VOICE_ID:value.voiceId,CARTESIA_API_VERSION:value.apiVersion,CARTESIA_MODEL:'sonic-3.6',GENERATION_ENABLED:row.enabled?'true':'false',MAX_DAILY_GENERATIONS:'1',__providerVault:true,__providerChecked:row.checked_revision===row.revision&&validation.kie?.ok===true&&validation.cartesia?.ok===true};}
async function saveProviderSettings(request,db,env,user){ownerOnly(user);await vaultKey(env);const b=await body(request,5000);if(!Number.isInteger(b.revision)||typeof b.enabled!=='boolean')fail('Invalid settings revision or test permission.');const {row,value}=await providerState(db,env);if((row?.revision||0)!==b.revision)fail('Settings changed in another window. Reload Connections before saving.',409);for(const name of ['kieKey','cartesiaKey']){if(b[name]!==undefined&&typeof b[name]!=='string')fail('Invalid provider key.');const key=b[name]?.trim();if(key){if(key.length<12||key.length>512||/\s/.test(key))fail('Enter the complete API key without spaces.');value[name]=key;}}
if(typeof b.voiceId!=='string'||!/^[a-zA-Z0-9_-]{8,120}$/.test(b.voiceId.trim()))fail('Enter the Sia voice ID from Cartesia.');if(typeof b.apiVersion!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(b.apiVersion))fail('Enter a valid Cartesia API version.');value.voiceId=b.voiceId.trim();value.apiVersion=b.apiVersion;if(!value.kieKey||!value.cartesiaKey)fail('Enter both provider API keys for first-time setup.');const sealed=await sealProvider(env,value);let result;
if(row)result=await db.prepare("UPDATE provider_settings SET body=?,revision=revision+1,enabled=?,checked_revision=0,validation='{}',updated_at=?,actor=? WHERE id='production' AND revision=?").bind(sealed,b.enabled?1:0,now(),user.email,b.revision).run();else result=await db.prepare("INSERT OR IGNORE INTO provider_settings (id,body,revision,enabled,checked_revision,validation,updated_at,actor) VALUES ('production',?,1,?,0,'{}',?,?)").bind(sealed,b.enabled?1:0,now(),user.email).run();if(!result.meta.changes)fail('Settings changed in another window. Reload Connections before saving.',409);await event(db,user,'Provider settings saved (values hidden)','provider-settings');return json(await providerSummary(db,env));}
async function checkProviderSettings(db,env,user){ownerOnly(user);const {row,value}=await providerState(db,env);if(!row)fail('Save both API keys and Sia voice ID first.');const previous=JSON.parse(row.validation);if(previous.at&&Date.now()-Date.parse(previous.at)<5000)fail('Wait a few seconds before checking again.',429);
const check=async(kind)=>{try{const isKie=kind==='kie';const r=await fetch(isKie?'https://api.kie.ai/api/v1/chat/credit':'https://api.cartesia.ai/voices/'+encodeURIComponent(value.voiceId),{method:'GET',redirect:'manual',signal:AbortSignal.timeout(20000),headers:isKie?{Authorization:'Bearer '+value.kieKey}:{Authorization:'Bearer '+value.cartesiaKey,'Cartesia-Version':value.apiVersion}});if(!r.ok)return {ok:false,message:kind==='kie'?'Kie could not verify this key. Check the key and account access.':'Cartesia could not verify this voice. Check the key, voice ID and API version.'};const data=await r.json();if(isKie){if(data.code!==200||!Number.isFinite(data.data))return {ok:false,message:'Kie returned an unrecognized credit response.'};return {ok:data.data>0,credits:data.data,message:data.data>0?'Kie key accepted; credits available.':'Kie key accepted, but no credits are available.'};}return {ok:data.id===value.voiceId&&data.status==='active',message:data.id===value.voiceId&&data.status==='active'?'Sia voice is accessible and active.':'This Cartesia voice is not active or does not match the saved ID.'};}catch(error){const safeName=['TypeError','TimeoutError','AbortError','SyntaxError'].includes(error?.name)?error.name:'NetworkError';let detail=String(error?.message||'Connection failed');for(const secret of [value.kieKey,value.cartesiaKey])if(secret)detail=detail.split(secret).join('[redacted]');detail=detail.replace(/Bearer\s+\S+/gi,'Bearer [redacted]').slice(0,300);console.error(JSON.stringify({event:'provider_check_failed',provider:kind,error:safeName,detail}));return {ok:false,message:'Connection check failed ('+safeName+'). No generation was started. The owner can inspect the server diagnostic.'}}};
const [kie,cartesia]=await Promise.all([check('kie'),check('cartesia')]);const result={kie,cartesia,at:now(),cost:'No audio or video was generated.'};const saved=await db.prepare("UPDATE provider_settings SET validation=?,checked_revision=? WHERE id='production' AND revision=?").bind(JSON.stringify(result),row.revision,row.revision).run();if(!saved.meta.changes)fail('Settings changed while the check ran. Check the current saved settings again.',409);await event(db,user,'Provider connections checked','provider-settings');return json(await providerSummary(db,env));}

export default {async fetch(request,env){try{const url=new URL(request.url),p=url.pathname;if(!p.startsWith('/api/')){const key=p==='/'?'/index.html':p;const asset=ASSETS[key];if(!asset)return new Response('Not found',{status:404});const ext=key.split('.').pop();const types={html:'text/html',js:'text/javascript',css:'text/css',json:'application/json',md:'text/plain',webp:'image/webp',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg'};return new Response(Uint8Array.from(atob(asset),x=>x.charCodeAt(0)),{headers:{'content-type':(types[ext]||'application/octet-stream')+(ext==='html'||ext==='js'||ext==='css'?'; charset=utf-8':''),'x-content-type-options':'nosniff','cache-control':'private, no-cache','referrer-policy':'same-origin'}});}
const user=await identity(request,env),db=store(env);if(!['GET','HEAD'].includes(request.method)){if(request.headers.get('origin')!==url.origin)fail('Same-origin request required.',403);writeAllowed(user);}
if(p.startsWith('/api/phase1/')){env=await providerEnvironment(db,env);return await handlePhase1(request,env,user,db,{json,body,event,ownerOnly,approveAllowed,readiness,uploadKie,providerJson,approvedProviderUrl,advanceJob});}
if(p==='/api/provider-settings'&&request.method==='GET'){ownerOnly(user);return json(await providerSummary(db,env));}
if(p==='/api/provider-settings'&&request.method==='PUT')return await saveProviderSettings(request,db,env,user);
if(p==='/api/provider-settings/check'&&request.method==='POST')return await checkProviderSettings(db,env,user);
if(p==='/api/session'||p.startsWith('/api/jobs'))env=await providerEnvironment(db,env);
if(p==='/api/session'&&request.method==='GET')return json({user,connections:readiness(env)});
if(p==='/api/workspace'&&request.method==='GET'){const row=await db.prepare("SELECT * FROM documents WHERE id='workspace'").first();return json(row?{state:JSON.parse(row.body),revision:row.revision}:{state:null,revision:0});}
if(p==='/api/workspace'&&request.method==='PUT'){const b=await body(request,3500000);if(!b.state||typeof b.state!=='object'||Array.isArray(b.state)||!Number.isInteger(b.revision))fail('Invalid workspace');delete b.state.role;delete b.state.keys;delete b.state.versions;delete b.state.jobs;const raw=JSON.stringify(b.state);if(/sk_car_|KIE_API_KEY|CARTESIA_API_KEY/.test(raw))fail('Do not store credentials in workspace records.');let r;if(b.revision===0)r=await db.prepare("INSERT OR IGNORE INTO documents(id,body,revision,updated_at,actor) VALUES ('workspace',?,1,?,?)").bind(raw,now(),user.email).run();else r=await db.prepare("UPDATE documents SET body=?,revision=revision+1,updated_at=?,actor=? WHERE id='workspace' AND revision=?").bind(raw,now(),user.email,b.revision).run();if(!r.meta.changes)fail('Another manager saved changes. Export your draft and reload before saving again.',409);await event(db,user,'Workspace saved','workspace');return json({revision:b.revision+1});}
if(p==='/api/versions'&&request.method==='GET'){const r=await db.prepare('SELECT * FROM versions ORDER BY created_at DESC').all();return json(r.results.map(parseRow));}
if(p==='/api/versions'&&request.method==='POST'){const b=await body(request);if(!/^SIA-2026-10-(0[1-9]|[12]\d|30)$/.test(b.lessonId))fail('Choose a lesson within October 1–30.');textValue(b.script,'script',6000);textValue(b.prompt,'prompt',50000);if(!Array.isArray(b.scenes)||!b.scenes.length||b.scenes.length>12)fail('Scenes are required.');if(b.parentId&&!await db.prepare('SELECT id FROM versions WHERE id=? AND lesson_id=?').bind(b.parentId,b.lessonId).first())fail('Parent version unavailable.');const vid=id();await db.prepare('INSERT INTO versions(id,lesson_id,body,parent_id,created_at,actor,status) VALUES (?,?,?,?,?,?,?)').bind(vid,b.lessonId,JSON.stringify(b),b.parentId||null,now(),user.email,'Draft').run();await event(db,user,'Version created',vid);return json(parseRow(await db.prepare('SELECT * FROM versions WHERE id=?').bind(vid).first()),201);}
if(p.match(/^\/api\/versions\/[^/]+\/approve$/)&&request.method==='POST'){approveAllowed(user);const vid=p.split('/')[3];const b=await body(request);if(!b.qa||!['identity','voice','captions','language','rights','safeZones'].every(k=>b.qa[k]===true))fail('Complete all final media checks.');const v=await db.prepare('SELECT * FROM versions WHERE id=?').bind(vid).first();if(!v)fail('Version not found.',404);const job=await db.prepare("SELECT * FROM jobs WHERE version_id=? AND status='Completed'").bind(vid).first();if(!job)fail('Generate and finish media before final approval. Planning approval does not approve a video.');fail('Presenter draft exists. Final captioned media upload and export validation must be connected before publishing approval.',409);}
if(p==='/api/jobs'&&request.method==='GET'){const r=await db.prepare('SELECT * FROM jobs ORDER BY created_at DESC LIMIT 200').all();return json(r.results.map(parseRow));}
if(p==='/api/jobs'&&request.method==='POST'){if(env.__providerVault)ownerOnly(user);const b=await body(request);if(!readiness(env).ready)return json({error:'Generation is waiting for secure provider setup.',missing:readiness(env).checks.filter(c=>!c.ready).map(c=>c.name)},409);const v=parseRow(await db.prepare('SELECT * FROM versions WHERE id=?').bind(b.versionId).first());if(!v)fail('Save a version first.');if(env.__providerVault&&(v.body.script.trim().split(/\s+/).length>40||!Number.isFinite(v.body.duration)||v.body.duration>15))fail('Use the short test draft from Connections first: at most 40 words and 15 planned seconds.');if(v.status==='Approved')fail('Approved versions are immutable. Create a new variation.');if(!v.body.referenceKey||!v.body.referenceApproved||!await env.BUCKET.head(v.body.referenceKey))fail('Upload and approve one clean Sia reference frame for this setting.');if(!v.body.rightsConfirmed)fail('Sia commercial rights confirmation is required.');const sceneIndex=b.sceneIndex??null;if(sceneIndex!==null&&(!Number.isInteger(sceneIndex)||!v.body.scenes[sceneIndex]))fail('Invalid scene.');const ik=v.id+':'+(sceneIndex??'all');const existing=await db.prepare('SELECT * FROM jobs WHERE idempotency_key=?').bind(ik).first();if(existing)return json(parseRow(existing));const jid=id(),stamp=now();const cap=Math.min(30,Math.max(1,Number(env.MAX_DAILY_GENERATIONS)||3));const inserted=await db.prepare("INSERT INTO jobs (id,version_id,idempotency_key,status,stage,body,created_at,updated_at) SELECT ?,?,?,'Queued','voice',?,?,? WHERE (SELECT COUNT(*) FROM jobs WHERE created_at>=?)<?").bind(jid,v.id,ik,JSON.stringify({sceneIndex,outputKind:'Uncaptioned presenter draft'}),stamp,stamp,env.__providerVault?'0000':stamp.slice(0,10),cap).run();if(!inserted.meta.changes)fail(env.__providerVault?'The one-test allowance has been used. Resume the existing job; saving keys does not create another allowance.':'Daily generation cap reached.',429);await event(db,user,'Generation queued',jid);return json(parseRow(await db.prepare('SELECT * FROM jobs WHERE id=?').bind(jid).first()),202);}
if(p.match(/^\/api\/jobs\/[^/]+\/advance$/)&&request.method==='POST'){const j=parseRow(await db.prepare('SELECT * FROM jobs WHERE id=?').bind(p.split('/')[3]).first());if(!j)fail('Job not found.',404);if(env.__providerVault){ownerOnly(user);if(env.GENERATION_ENABLED!=='true'&&j.stage!=='poll')fail('Test generation is paused in Connections.',409);}return json(await advanceJob(db,env,j));}
if(p==='/api/reference'&&request.method==='POST'){const type=request.headers.get('content-type');if(!['image/png','image/jpeg','image/webp'].includes(type))fail('PNG, JPEG or WebP required.');const bytes=await request.arrayBuffer();if(bytes.byteLength>5*1024*1024)fail('Reference must be under 5 MB.',413);const key='references/'+id();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type}});await event(db,user,'Reference frame uploaded',key);return json({key},201);}
if(p==='/api/media'&&['GET','HEAD'].includes(request.method)){const key=url.searchParams.get('key');if(!key||!/^(?:references\/[a-f0-9-]+|jobs\/[a-f0-9-]+\/(?:voice\.wav|draft\.mp4|audio-\d+\.wav|clip-\d+\.mp4)|finals\/[a-f0-9-]+\.(?:mp4|webm))$/.test(key))fail('Invalid media key.');const head=await env.BUCKET.head(key);if(!head)fail('Media not found.',404);const size=Number(head.size)||0;const headers={'content-type':head.httpMetadata?.contentType||'application/octet-stream','cache-control':'private, no-store','x-content-type-options':'nosniff','accept-ranges':'bytes'};const range=request.headers.get('range');let status=200,offset=0,length=size;if(range){const m=/^bytes=(\d*)-(\d*)$/.exec(range.trim());let end;if(m&&m[1]===''&&m[2]!==''){length=Math.min(size,Number(m[2]));offset=size-length;end=size-1;}else if(m&&m[1]!==''){offset=Number(m[1]);end=m[2]===''?size-1:Math.min(size-1,Number(m[2]));length=end-offset+1;}if(!m||(m[1]===''&&m[2]==='')||offset>=size||length<=0)return new Response(null,{status:416,headers:{...headers,'content-range':'bytes */'+size}});status=206;headers['content-range']='bytes '+offset+'-'+(offset+length-1)+'/'+size;}headers['content-length']=String(length);if(request.method==='HEAD')return new Response(null,{status,headers});const object=await env.BUCKET.get(key,status===206?{range:{offset,length}}:undefined);if(!object)fail('Media not found.',404);return new Response(object.body,{status,headers});}
if(p==='/api/audit'&&request.method==='GET'){const r=await db.prepare('SELECT * FROM events ORDER BY at DESC LIMIT 100').all();return json(r.results);}
if(p==='/api/members'&&request.method==='GET'){if(user.role!=='Owner')fail('Owner access required.',403);return json((await db.prepare('SELECT email,role FROM members').all()).results);}
return json({error:'This operation is not connected.'},404);
}catch(e){if(!e.status||e.status>=500)console.error(JSON.stringify({event:'request_failed',path:new URL(request.url).pathname,status:e.status||503}));return json({error:e.status?e.message:'The service is unavailable. Your unsaved input is preserved; retry after checking connection.'},e.status||503);}}};
