/* Local media finishing. No provider calls or automatic publishing. */
const SiaFinishing=(()=>{
 const $=tag=>document.createElement(tag);
 const REQUESTED_CAPTURE_FPS=60; // Capture headroom only; the server validates actual MP4 sample timing.
 function supportedMime(){if(typeof MediaRecorder==='undefined')return null;return ['video/mp4;codecs=avc1.424028,mp4a.40.2','video/mp4;codecs=avc1,mp4a.40.2','video/mp4;codecs=avc1.640028,mp4a.40.2'].find(t=>MediaRecorder.isTypeSupported(t))||null;}
 function wait(el,event,timeout=20000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>finish(Error('Media took too long to load.')),timeout);const good=()=>finish(),bad=()=>finish(Error('Media could not be decoded.'));function finish(error){clearTimeout(timer);el.removeEventListener(event,good);el.removeEventListener('error',bad);error?reject(error):resolve();}el.addEventListener(event,good,{once:true});el.addEventListener('error',bad,{once:true});});}
 async function blobUrl(url,signal){const r=await fetch(url,{signal});if(!r.ok)throw Error('Source media is unavailable.');return URL.createObjectURL(await r.blob());}
 async function loadVideo(url,recorded=false){const video=$('video');video.preload='auto';video.playsInline=true;video.muted=true;const ready=wait(video,'loadeddata');video.src=url;video.load();await ready;if(!video.videoWidth||(!recorded&&!Number.isFinite(video.duration))||video.duration<=0)throw Error('Source video has invalid dimensions or duration.');return video;}
 function validateCaptions(cues,duration){if(!Array.isArray(cues)||!cues.length)throw Error('Add captions before rendering.');cues.forEach((c,i)=>{if(typeof c.text!=='string'||!c.text.trim()||!Number.isFinite(c.start)||!Number.isFinite(c.end)||c.start<0||c.end<=c.start||c.end>duration+.5||(i&&c.start<cues[i-1].end-.01))throw Error('Caption '+(i+1)+' has invalid or overlapping timing.');if(c.text.trim().split(/\s+/).length>8)throw Error('Caption '+(i+1)+' exceeds eight words. Split it into shorter cues.');});return cues;}
 function captionLines(ctx,text,maxWidth){const words=text.split(/\s+/),lines=[];let line='';for(const w of words){const candidate=line?line+' '+w:w;if(ctx.measureText(candidate).width>maxWidth&&line){lines.push(line);line=w;}else line=candidate;}if(line)lines.push(line);return lines;}
 function validateBroll(plan,duration){
  if(!Array.isArray(plan)||plan.length<2||plan.length>3)throw Error('Plan two or three teaching-card B-roll inserts before rendering.');
  let total=0;plan.forEach((item,i)=>{const length=item.end-item.start;if(item.type!=='teaching-card'||typeof item.text!=='string'||!item.text.trim())throw Error('B-roll '+(i+1)+' needs teaching-card text.');if(!Number.isFinite(item.start)||!Number.isFinite(item.end)||item.start<0||item.end>duration-.15||length<1.5||length>3||(i&&item.start<plan[i-1].end))throw Error('B-roll '+(i+1)+' must last 1.5–3 seconds, stay within the voice, and not overlap.');for(const key of ['visual','purpose','shot','transition','voiceover','captionTreatment','returnToSia'])if(typeof item[key]!=='string'||!item[key].trim())throw Error('B-roll '+(i+1)+' is missing '+key+'.');if(item.text.trim().split(/\s+/).length>20)throw Error('Keep B-roll teaching text to twenty words or fewer.');total+=length;});if(total>=duration/2)throw Error('Sia must remain visible for most of the video.');return plan;
 }
 function stereoAudioGraph(context,audio){
  const source=context.createMediaElementSource(audio),mono=context.createGain(),stereo=context.createChannelMerger(2),analyser=context.createAnalyser(),destination=context.createMediaStreamDestination();
  // The approved Cartesia voice is mono. Put the same voice in both AAC channels.
  mono.channelCount=1;mono.channelCountMode='explicit';mono.channelInterpretation='speakers';source.connect(mono);mono.connect(stereo,0,0);mono.connect(stereo,0,1);analyser.channelCount=2;analyser.channelCountMode='explicit';stereo.connect(analyser);destination.channelCount=2;destination.channelCountMode='explicit';destination.channelInterpretation='speakers';analyser.connect(destination);analyser.fftSize=256;return {source,mono,stereo,analyser,destination};
 }
 function retentionZoom(time){const beat=Math.floor(time/3),progress=Math.min(1,(time%3)/.35),ease=progress*progress*(3-2*progress);return 1+.045*(beat%2?ease:beat?1-ease:0);}
 function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
 function teachingCard(ctx,item,time){
  const w=ctx.canvas.width,h=ctx.canvas.height,elapsed=time-item.start,remaining=item.end-time;
  ctx.save();ctx.globalAlpha=Math.max(0,Math.min(1,elapsed/.15,remaining/.15));
  const gradient=ctx.createLinearGradient(0,0,w,h);gradient.addColorStop(0,'#101f2c');gradient.addColorStop(1,'#243e43');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);
  ctx.fillStyle='rgba(255,138,61,.10)';ctx.beginPath();ctx.arc(w*.94,h*.21,w*.58,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(158,221,200,.07)';ctx.beginPath();ctx.arc(w*.10,h*.68,w*.48,0,Math.PI*2);ctx.fill();
  const rise=22*(1-Math.min(1,elapsed/.3));ctx.fillStyle='#ff8a3d';rounded(ctx,100,500+rise,72,7,3);ctx.font='700 24px Arial, sans-serif';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText('SPEAK WITH CONFIDENCE',100,559+rise);
  let size=76,lines;do{ctx.font='700 '+size+'px Arial, sans-serif';lines=captionLines(ctx,item.text,w-240);if(lines.length<=4&&lines.every(line=>ctx.measureText(line).width<=w-240))break;size-=2;}while(size>42);if(lines.length>4||lines.some(line=>ctx.measureText(line).width>w-240))throw Error('B-roll teaching text is too long to display safely.');ctx.fillStyle='#ffffff';lines.forEach((line,i)=>ctx.fillText(line,100,680+rise+i*size*1.28));
  ctx.fillStyle='rgba(255,255,255,.20)';rounded(ctx,100,1150,740,4,2);ctx.fillStyle='#ff8a3d';rounded(ctx,100,1150,Math.max(4,740*elapsed/(item.end-item.start)),4,2);ctx.restore();ctx.globalAlpha=1;
 }
 function highlightWords(text,terms){const clean=v=>v.replace(/[^\p{L}\p{N}']/gu,'').toLowerCase();const words=text.split(/\s+/),normalized=words.map(clean),indices=new Set();for(const term of terms){const tokens=String(term).trim().split(/\s+/).map(clean).filter(Boolean);if(!tokens.length)continue;for(let i=0;i<=words.length-tokens.length;i++)if(tokens.every((token,j)=>token===normalized[i+j]))for(let j=0;j<tokens.length;j++)indices.add(i+j);}return indices;}
 function draw(ctx,video,time,settings,cues,logo,broll=[],terms=[]){
  const w=ctx.canvas.width,h=ctx.canvas.height;ctx.globalAlpha=1;ctx.fillStyle='#152332';ctx.fillRect(0,0,w,h);
  const vw=video.videoWidth,vh=video.videoHeight,scale=Math.max(w/vw,h/vh)*retentionZoom(time),dw=vw*scale,dh=vh*scale;
  // Fill the complete 9:16 canvas without stretching; legacy fit settings cannot add bars.
  ctx.drawImage(video,(w-dw)*Math.max(0,Math.min(1,settings.focusX??.5)),(h-dh)/2,dw,dh);
  const insert=broll.find(c=>time>=c.start&&time<c.end);if(insert)teachingCard(ctx,insert,time);
  const cue=cues.find(c=>time>=c.start&&time<c.end);if(cue){let size=60,lines;do{ctx.font='700 '+size+'px Arial, sans-serif';lines=captionLines(ctx,cue.text,w*.76);if(lines.length<=2&&lines.every(line=>ctx.measureText(line).width<=w*.76))break;size-=2;}while(size>=46);if(lines.length>2||lines.some(line=>ctx.measureText(line).width>w*.76))throw Error('A caption is too long. Split it into shorter cues.');const lineHeight=size*1.3,y=h*.73-(lines.length-1)*lineHeight/2;ctx.fillStyle='rgba(8,12,18,.88)';rounded(ctx,w*.07,y-lineHeight*.66,w*.80,lineHeight*(lines.length+.35),18);ctx.textAlign='left';ctx.textBaseline='middle';const highlighted=highlightWords(cue.text,terms);let wordIndex=0;for(let i=0;i<lines.length;i++){let x=w*.47-ctx.measureText(lines[i]).width/2;for(const word of lines[i].split(/\s+/)){ctx.fillStyle=highlighted.has(wordIndex++)?'#ff8a3d':'#ffffff';ctx.fillText(word,x,y+i*lineHeight);x+=ctx.measureText(word+' ').width;}}}
  if(logo&&settings.logo!==false&&time>=2){const size=w*.105;ctx.drawImage(logo,w*.08,h*.10,size,size);}
 }
 async function render({job,captions,settings={},onProgress=()=>{},signal}){
  const mime=supportedMime();if(!mime)throw Error('This browser cannot export H.264/AAC MP4. Use current Chrome or Safari with MP4 recording support.');if(!window.ReelTools?.toSrt)throw Error('Caption tools have not loaded. Reload before rendering.');if(document.hidden)throw Error('Keep this tab visible during rendering.');
  const urls=[],videos=[];let context,stream,recorder,tick,watchdog,audio;let cancelled=false;
  const abort=()=>{cancelled=true;if(recorder?.state==='recording')recorder.stop();};const visibility=()=>{if(document.hidden)abort();};
  try{
   const clips=(job.body.clips?.length?job.body.clips:[{start:0,end:job.body.audioDuration,mediaKey:job.body.mediaKey}]).filter(c=>c.mediaKey);if(!clips.length)throw Error('Generate the source Sia video first.');
   const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)throw Error('This browser cannot produce stereo audio.');context=new AudioCtx({sampleRate:48000});await context.resume();
   for(const clip of clips){const url=await blobUrl('/api/media?key='+encodeURIComponent(clip.mediaKey),signal);urls.push(url);const video=await loadVideo(url);if(Number.isFinite(clip.end)&&video.duration<clip.end-(clip.start||0)-.2)throw Error('A provider clip is shorter than its voice segment. Review or regenerate it.');videos.push(video);}
   audio=$('audio');audio.preload='auto';audio.muted=false;audio.volume=1;const audioUrl=await blobUrl('/api/media?key='+encodeURIComponent(job.body.audioKey),signal);urls.push(audioUrl);const audioReady=wait(audio,'canplay');audio.src=audioUrl;audio.load();await audioReady;
   const duration=audio.duration;if(!Number.isFinite(duration)||duration<=0||duration>150)throw Error('Voice duration is invalid.');validateCaptions(captions,duration);const broll=validateBroll(job.body.production?.broll,duration),terms=job.body.production?.highlightTerms||[];const actualBroll=broll.map(c=>({...c,renderedFrames:0,firstRenderedTime:null,lastRenderedTime:null}));
   const canvas=$('canvas');canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext('2d');let logo=null;if(settings.logo!==false){logo=new Image();logo.src='/assets/speakx.png';await logo.decode();}
   const {analyser,destination}=stereoAudioGraph(context,audio);const samples=new Uint8Array(analyser.fftSize);let heardAudio=false,frames=0,lastTime=0,current=0,switchedAt=0;
   const visualStream=canvas.captureStream(REQUESTED_CAPTURE_FPS);stream=new MediaStream([...visualStream.getVideoTracks(),...destination.stream.getAudioTracks()]);
   recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:5500000,audioBitsPerSecond:192000});const chunks=[];let recorderError=null;
   const done=new Promise((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=e=>{recorderError=e.error||Error('Video encoding failed.');reject(recorderError);};recorder.onstop=resolve;});
   const paint=()=>{if(cancelled)return;try{const t=audio.currentTime;lastTime=t;const next=Math.max(0,clips.findIndex((c,i)=>t>=(c.start||0)&&(t<(c.end??duration)||i===clips.length-1)));if(next!==current){videos[current].pause();current=next;switchedAt=t;videos[current].currentTime=Math.max(0,t-(clips[current].start||0));videos[current].play().catch(()=>abort());}const expected=t-(clips[current].start||0);if(t-switchedAt>.4&&(videos[current].readyState<2||Math.abs(videos[current].currentTime-expected)>.3))throw Error('Video playback drifted from the voice. Nothing was saved; retry or review the source clip.');draw(ctx,videos[current],t,settings,captions,logo,broll,terms);for(const insert of actualBroll)if(t>=insert.start&&t<insert.end){insert.renderedFrames++;insert.firstRenderedTime??=t;insert.lastRenderedTime=t;}analyser.getByteTimeDomainData(samples);if(samples.some(v=>Math.abs(v-128)>2))heardAudio=true;frames++;onProgress({fraction:Math.min(1,t/duration),seconds:t,duration});tick=requestAnimationFrame(paint);}catch(e){recorderError=e;abort();}};
   signal?.addEventListener('abort',abort,{once:true});document.addEventListener('visibilitychange',visibility);if(signal?.aborted)throw Error('Render cancelled.');
   audio.onended=()=>{cancelAnimationFrame(tick);if(recorder.state==='recording')recorder.stop();};audio.onerror=()=>{recorderError=Error('Voice playback failed.');abort();};
   draw(ctx,videos[0],0,settings,captions,logo,broll,terms);watchdog=setTimeout(()=>{recorderError=Error('Rendering stalled. Keep the tab visible and try again.');abort();},(duration+30)*1000);recorder.start(1000);await Promise.race([(async()=>{await videos[0].play();if(cancelled)return;await audio.play();if(!cancelled)paint();})(),done]);await done;
   audio.pause();videos.forEach(v=>v.pause());if(recorderError)throw recorderError;if(cancelled)throw Error('Render cancelled or tab hidden. Nothing was saved. Keep this tab visible and retry.');if(!heardAudio||frames<3||lastTime<duration-.7)throw Error('Finished video did not include the complete audible take. Retry without leaving the tab.');
   if(actualBroll.some(c=>c.renderedFrames<2||c.firstRenderedTime>c.start+.2||c.lastRenderedTime<c.end-.2))throw Error('A planned B-roll insert was not fully rendered. Retry with this tab visible.');const result=new Blob(chunks,{type:recorder.mimeType});if(result.size<1000)throw Error('Video encoder produced an empty file.');if(result.size>60*1024*1024)throw Error('Finished video exceeds 60 MB; shorten it.');
   const resultUrl=URL.createObjectURL(result);urls.push(resultUrl);const check=await loadVideo(resultUrl,true);if(check.videoWidth!==1080||check.videoHeight!==1920)throw Error('Finished video dimensions are invalid.');
   return {blob:result,metadata:{width:check.videoWidth,height:check.videoHeight,duration,captions,captionSrt:window.ReelTools.toSrt(captions),actualBroll,audioPresent:heardAudio,technicalExpectations:{width:1080,height:1920,fps:30,container:'mp4',videoCodec:'h264',audioCodec:'aac',channels:2},renderSettings:{...settings,fit:'cover',width:1080,height:1920,requestedFps:REQUESTED_CAPTURE_FPS,minimumFps:30,channels:2,videoCodec:'h264',audioCodec:'aac',audioMix:'Approved Sia mono voice duplicated into left and right channels',broll,highlightTerms:terms,retentionZoomEverySeconds:3,transitionSeconds:.15,paintedFrames:frames,renderer:'Browser real-time canvas + original Cartesia audio',mime:recorder.mimeType},notes:'Review the finished file for caption timing, complete speech, visuals and lip-sync before approving.'}};
  }finally{audio?.pause();if(audio){audio.removeAttribute('src');audio.load();}clearTimeout(watchdog);cancelAnimationFrame(tick);if(recorder?.state==='recording')recorder.stop();videos.forEach(v=>{v.pause();v.removeAttribute('src');v.load();});stream?.getTracks().forEach(t=>t.stop());await context?.close().catch(()=>{});urls.forEach(u=>URL.revokeObjectURL(u));signal?.removeEventListener('abort',abort);document.removeEventListener('visibilitychange',visibility);}
 }
 return {render,supportedMime,validateCaptions,validateBroll,captionLines,retentionZoom,stereoAudioGraph,draw};
})();
