/* Local media finishing. No provider calls or automatic publishing. */
const SiaFinishing=(()=>{
 const $=tag=>document.createElement(tag);
 function supportedMime(){if(typeof MediaRecorder==='undefined')return null;return ['video/mp4;codecs=avc1.424028,mp4a.40.2','video/mp4;codecs=avc1,mp4a.40.2','video/mp4','video/webm;codecs=vp8,opus','video/webm'].find(t=>MediaRecorder.isTypeSupported(t))||null;}
 function wait(el,event,timeout=20000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>finish(Error('Media took too long to load.')),timeout);const good=()=>finish(),bad=()=>finish(Error('Media could not be decoded.'));function finish(error){clearTimeout(timer);el.removeEventListener(event,good);el.removeEventListener('error',bad);error?reject(error):resolve();}el.addEventListener(event,good,{once:true});el.addEventListener('error',bad,{once:true});});}
 async function blobUrl(url,signal){const r=await fetch(url,{signal});if(!r.ok)throw Error('Source media is unavailable.');return URL.createObjectURL(await r.blob());}
 async function loadVideo(url,recorded=false){const video=$('video');video.preload='auto';video.playsInline=true;video.muted=true;const ready=wait(video,'loadeddata');video.src=url;video.load();await ready;if(!video.videoWidth||(!recorded&&!Number.isFinite(video.duration))||video.duration<=0)throw Error('Source video has invalid dimensions or duration.');return video;}
 function validateCaptions(cues,duration){if(!Array.isArray(cues)||!cues.length)throw Error('Add captions before rendering.');cues.forEach((c,i)=>{if(typeof c.text!=='string'||!c.text.trim()||!Number.isFinite(c.start)||!Number.isFinite(c.end)||c.start<0||c.end<=c.start||c.end>duration+.5||(i&&c.start<cues[i-1].end-.01))throw Error('Caption '+(i+1)+' has invalid or overlapping timing.');});return cues;}
 function captionLines(ctx,text,maxWidth){const words=text.split(/\s+/),lines=[];let line='';for(const w of words){const candidate=line?line+' '+w:w;if(ctx.measureText(candidate).width>maxWidth&&line){lines.push(line);line=w;}else line=candidate;}if(line)lines.push(line);return lines;}
 function draw(ctx,video,time,settings,cues,logo){const w=ctx.canvas.width,h=ctx.canvas.height;ctx.fillStyle=settings.background||'#152332';ctx.fillRect(0,0,w,h);const vw=video.videoWidth,vh=video.videoHeight;const scale=settings.fit==='contain'?Math.min(w/vw,h/vh):Math.max(w/vw,h/vh);const dw=vw*scale,dh=vh*scale;const x=(w-dw)*Math.max(0,Math.min(1,settings.focusX??.5));ctx.drawImage(video,x,(h-dh)/2,dw,dh);
  const cue=cues.find(c=>time>=c.start&&time<c.end);if(cue){let size=settings.fontSize||42;ctx.textAlign='center';ctx.textBaseline='middle';let lines=[];do{ctx.font='700 '+size+'px Arial, sans-serif';lines=captionLines(ctx,cue.text,w*.78);if(lines.length<=2)break;size-=2;}while(size>20);if(lines.length>2)throw Error('A caption is too long. Split it into shorter cues.');const lineHeight=size*1.3,y=h*.72-(lines.length-1)*lineHeight/2;ctx.fillStyle='rgba(8,12,18,.84)';ctx.fillRect(w*.07,y-lineHeight*.7,w*.80,lineHeight*(lines.length+.4));ctx.fillStyle='#fff';lines.forEach((line,i)=>ctx.fillText(line,w*.47,y+i*lineHeight));}
  if(logo&&settings.logo!==false&&time>=2){const size=w*.12;ctx.drawImage(logo,w*.07,h*.06,size,size);} }
 async function render({job,captions,settings={},onProgress=()=>{},signal}){
  const mime=supportedMime();if(!mime)throw Error('This browser cannot record finished video. Use current Chrome.');if(document.hidden)throw Error('Keep this tab visible during rendering.');
  const urls=[],videos=[];let context,stream,recorder,tick,watchdog,audio;let cancelled=false;
  const abort=()=>{cancelled=true;if(recorder?.state==='recording')recorder.stop();};const visibility=()=>{if(document.hidden)abort();};
  try{
   const clips=(job.body.clips?.length?job.body.clips:[{start:0,end:job.body.audioDuration,mediaKey:job.body.mediaKey}]).filter(c=>c.mediaKey);if(!clips.length)throw Error('Generate the source Sia video first.');
   const AudioCtx=window.AudioContext||window.webkitAudioContext;context=new AudioCtx();await context.resume();
   for(const clip of clips){const url=await blobUrl('/api/media?key='+encodeURIComponent(clip.mediaKey),signal);urls.push(url);const video=await loadVideo(url);if(Number.isFinite(clip.end)&&video.duration<clip.end-(clip.start||0)-.2)throw Error('A provider clip is shorter than its voice segment. Review or regenerate it.');videos.push(video);}
   audio=$('audio');audio.preload='auto';audio.muted=false;audio.volume=1;const audioUrl=await blobUrl('/api/media?key='+encodeURIComponent(job.body.audioKey),signal);urls.push(audioUrl);const audioReady=wait(audio,'canplay');audio.src=audioUrl;audio.load();await audioReady;
   const duration=audio.duration;if(!Number.isFinite(duration)||duration<=0||duration>150)throw Error('Voice duration is invalid.');validateCaptions(captions,duration);
   const canvas=$('canvas');canvas.width=720;canvas.height=1280;const ctx=canvas.getContext('2d');let logo=null;if(settings.logo!==false){logo=new Image();logo.src='/assets/speakx.png';await logo.decode();}
   const source=context.createMediaElementSource(audio),analyser=context.createAnalyser(),destination=context.createMediaStreamDestination();source.connect(analyser);analyser.connect(destination);analyser.fftSize=256;const samples=new Uint8Array(analyser.fftSize);let heardAudio=false,frames=0,lastTime=0,current=0,switchedAt=0;
   const visualStream=canvas.captureStream(30);stream=new MediaStream([...visualStream.getVideoTracks(),...destination.stream.getAudioTracks()]);
   recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:4000000,audioBitsPerSecond:128000});const chunks=[];let recorderError=null;
   const done=new Promise((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=e=>{recorderError=e.error||Error('Video encoding failed.');reject(recorderError);};recorder.onstop=resolve;});
   const paint=()=>{if(cancelled)return;try{const t=audio.currentTime;lastTime=t;const next=Math.max(0,clips.findIndex((c,i)=>t>=(c.start||0)&&(t<(c.end??duration)||i===clips.length-1)));if(next!==current){videos[current].pause();current=next;switchedAt=t;videos[current].currentTime=Math.max(0,t-(clips[current].start||0));videos[current].play().catch(()=>abort());}const expected=t-(clips[current].start||0);if(t-switchedAt>.4&&(videos[current].readyState<2||Math.abs(videos[current].currentTime-expected)>.3))throw Error('Video playback drifted from the voice. Nothing was saved; retry or review the source clip.');draw(ctx,videos[current],t,settings,captions,logo);analyser.getByteTimeDomainData(samples);if(samples.some(v=>Math.abs(v-128)>2))heardAudio=true;frames++;onProgress({fraction:Math.min(1,t/duration),seconds:t,duration});tick=requestAnimationFrame(paint);}catch(e){recorderError=e;abort();}};
   signal?.addEventListener('abort',abort,{once:true});document.addEventListener('visibilitychange',visibility);if(signal?.aborted)throw Error('Render cancelled.');
   audio.onended=()=>{cancelAnimationFrame(tick);if(recorder.state==='recording')recorder.stop();};audio.onerror=()=>{recorderError=Error('Voice playback failed.');abort();};
   draw(ctx,videos[0],0,settings,captions,logo);watchdog=setTimeout(()=>{recorderError=Error('Rendering stalled. Keep the tab visible and try again.');abort();},(duration+30)*1000);recorder.start(1000);await Promise.race([(async()=>{await videos[0].play();if(cancelled)return;await audio.play();if(!cancelled)paint();})(),done]);await done;
   audio.pause();videos.forEach(v=>v.pause());if(recorderError)throw recorderError;if(cancelled)throw Error('Render cancelled or tab hidden. Nothing was saved. Keep this tab visible and retry.');if(!heardAudio||frames<3||lastTime<duration-.7)throw Error('Finished video did not include the complete audible take. Retry without leaving the tab.');
   const result=new Blob(chunks,{type:recorder.mimeType});if(result.size<1000)throw Error('Video encoder produced an empty file.');if(result.size>60*1024*1024)throw Error('Finished video exceeds 60 MB; shorten it.');
   const resultUrl=URL.createObjectURL(result);urls.push(resultUrl);const check=await loadVideo(resultUrl,true);if(Math.abs(check.videoWidth/check.videoHeight-9/16)>.025)throw Error('Finished video dimensions are invalid.');
   return {blob:result,metadata:{width:check.videoWidth,height:check.videoHeight,duration,captions,audioPresent:heardAudio,renderSettings:{...settings,renderer:'Browser real-time canvas + original Cartesia audio',mime:recorder.mimeType},notes:'Review the finished file for caption timing, complete speech, visuals and lip-sync before approving.'}};
  }finally{audio?.pause();if(audio){audio.removeAttribute('src');audio.load();}clearTimeout(watchdog);cancelAnimationFrame(tick);if(recorder?.state==='recording')recorder.stop();videos.forEach(v=>{v.pause();v.removeAttribute('src');v.load();});stream?.getTracks().forEach(t=>t.stop());await context?.close().catch(()=>{});urls.forEach(u=>URL.revokeObjectURL(u));signal?.removeEventListener('abort',abort);document.removeEventListener('visibilitychange',visibility);}
 }
 return {render,supportedMime,validateCaptions,captionLines};
})();
