/* Dedicated Phase 1 script → video → approved download workspace. */
const PhaseOne=(()=>{
 const P={ideas:[],exports:[],readiness:null,content:null,draft:null,revision:0,history:{versions:[],jobs:[],exports:[],events:[]},selected:null,tab:'Script',dirty:false,saving:false,saveQueue:Promise.resolve(),pending:new Map(),runners:new Set(),finishing:null,renderDrafts:{},controller:null,message:''};
 const q=s=>document.querySelector(s),h=s=>esc(s??''),api1=(path,method='GET',body)=>api('phase1/'+path,{method,body});
 const fields=[['title','Working title'],['platform','Platform'],['audience','Target audience'],['objective','Content objective'],['funnelStage','Funnel stage'],['format','Video format'],['duration','Recommended duration (seconds)'],['language','Language'],['pillar','Content pillar'],['keyword','Search keyword'],['hook','Selected hook'],['cta','CTA']];
 const QA=['identity','voice','captions','language','rights','safeZones','lipSync','visuals','audio','complete'];
 const stamp=s=>s?new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':'Not saved';
 const versionLabel=v=>'Script V'+(v.body.versionNumber||P.history.versions.slice().reverse().findIndex(x=>x.id===v.id)+1)+' — '+(v.body.name||v.body.note||'Saved script');
 const videoLabel=j=>'Video V'+(P.history.jobs.slice().reverse().findIndex(x=>x.id===j.id)+1);
 const media=k=>'/api/media?key='+encodeURIComponent(k);
 function notify(message){P.message=message;const el=q('#p1Message');if(el)el.textContent=message;else toast(message);}
 async function action(fn){try{await fn();}catch(e){notify(e.message+(e.missing?' Needed: '+e.missing.join(', '):''));}}
 async function bootstrap(){const [ideas,exports,readiness]=await Promise.all([api1('ideas'),api1('exports'),api1('readiness')]);P.ideas=ideas;P.exports=exports;P.readiness=readiness;}
 function content(id){return byId(id)||P.ideas.find(x=>x.body.contentId===id)?.body;}
 function initial(e){const script=e.script||e.target||'';return {lessonId:e.id||e.contentId,title:e.topic||e.title,platform:e.platform||'Instagram',audience:e.persona||e.audience||'Indian adults learning spoken English',objective:e.contentJob||e.objective||'Engagement',funnelStage:e.funnelStage||'Awareness',format:e.settingMode||e.format||'Sia direct lesson',duration:Number(e.duration)||30,language:e.language||'Hinglish',pillar:e.pillar||'Practical English',keyword:e.searchTerms?.[0]||e.keyword||'',hook:e.hook||'',script,voiceover:script,dialogue:e.dialogue||'Sia only; counterpart questions appear as text.',onScreenText:e.thumbnailCopy||'',captionText:script,cta:e.cta||'Bolke dekho.',prompt:withSiaReferencePolicy(e.finalPrompt||'Only Sia in a simple studio. Preserve the selected reference face and outfit. Accurate lip sync to the supplied voice. No other people or voices.'),scenes:structuredClone(e.scenes||[{startSeconds:0,endSeconds:Number(e.duration)||30,voiceover:script,captionText:script,shot:'Sia alone, direct to camera.',edit:'One clear learning point.',pauseSeconds:2}]),referenceKey:'',referenceApproved:false,rightsConfirmed:true,name:'Initial draft',note:'',parentId:null};}
 async function loadHistory(){P.history=await api1('history?lessonId='+encodeURIComponent(P.content.id||P.content.contentId));P.history.versions.sort((a,b)=>(b.body.versionNumber||0)-(a.body.versionNumber||0)||b.created_at.localeCompare(a.created_at));versions=await api('versions');jobs=await api('jobs');P.exports=await api1('exports');}
 async function open(id,tab='Script'){
  if(P.dirty){capture();await saveDraft();if(P.dirty)return;}
  const e=content(id);if(!e)return toast('Content idea not found.');P.content=e;P.tab=['Script','Review','Versions','Generate','Finish','Final Review','History'].includes(tab)?tab:'Script';P.message='';P.finishing=null;
  const [history,draft,readiness]=await Promise.all([api1('history?lessonId='+encodeURIComponent(id)),api1('drafts/'+encodeURIComponent(id)),api1('readiness')]);P.readiness=readiness;P.history=history;P.renderDrafts=draft.body?.renderDrafts||{};P.revision=draft.revision;P.selected=draft.body?.selectedVersionId||history.versions[0]?.id||null;P.draft=draft.body?.draft||structuredClone(history.versions[0]?.body||initial(e));P.dirty=false;show();
 }
 function capture(){if(!P.draft)return;if(q('#p1Captions')&&P.finishing){let captions;try{captions=JSON.parse(q('#p1Captions').value);}catch{throw Error('Caption cues must be valid JSON. Your edits remain on screen.');}P.renderDrafts[P.finishing]={captions,settings:{fit:q('#p1Fit').value,focusX:Number(q('#p1Focus').value),logo:q('#p1Logo').checked}};}document.querySelectorAll('[data-p1-field]').forEach(el=>{const k=el.dataset.p1Field;P.draft[k]=k==='duration'?Number(el.value):el.value;});document.querySelectorAll('[data-p1-check]').forEach(el=>P.draft[el.dataset.p1Check]=el.checked);if(q('#p1Scenes')){try{P.draft.scenes=JSON.parse(q('#p1Scenes').value);}catch{throw Error('Scene plan must be valid JSON. Your text is still on screen.');}}}
 function changed(){P.dirty=true;const status=q('#p1SaveStatus');if(status)status.textContent='Unsaved edits';}
 async function saveDraft(){const contentId=P.draft.lessonId,snapshot=structuredClone(P.draft),selectedVersionId=P.selected;P.saveQueue=P.saveQueue.catch(()=>{}).then(async()=>{const result=await api1('drafts/'+encodeURIComponent(contentId),'PUT',{revision:P.revision,body:{draft:snapshot,selectedVersionId,renderDrafts:structuredClone(P.renderDrafts)}});if(P.draft.lessonId===contentId){P.revision=result.revision;if(JSON.stringify(P.draft)===JSON.stringify(snapshot))P.dirty=false;const status=q('#p1SaveStatus');if(status)status.textContent='Draft saved · '+stamp(result.updatedAt);}});await P.saveQueue;notify('Draft saved to your private workspace.');}
 async function saveVersion(){capture();const parent=P.selected;const snapshot={...structuredClone(P.draft),parentId:parent,name:P.draft.name||'Updated script',note:P.draft.note||'Saved as a new version'};delete snapshot.pendingGeneration;const v=await api1('versions','POST',snapshot);P.selected=v.id;P.draft=structuredClone(v.body);P.dirty=true;await loadHistory();await saveDraft();notify(versionLabel(v)+' saved.');show();return v;}
 function input(k,label){return `<label>${h(label)}<input data-p1-field="${k}" ${k==='duration'?'type="number" min="1" max="120"':''} value="${h(P.draft[k])}"></label>`;}
 function textarea(k,label,rows=3){return `<label>${h(label)}<textarea data-p1-field="${k}" rows="${rows}">${h(P.draft[k])}</textarea></label>`;}
 function scriptView(){const selected=P.history.versions.find(x=>x.id===P.selected);return `${selected?.status==='Script approved'?'<p class="p1-warning">This script is already approved. Save your changes as a new version? Saving here always creates a new version and keeps the approved script intact.</p>':''}<div class="p1-meta">${fields.map(([k,l])=>input(k,l)).join('')}</div><div class="split"><section>${textarea('script','Full spoken script · sent to Cartesia',9)}${textarea('dialogue','Dialogue / counterpart text',3)}${textarea('voiceover','Voiceover transcript',5)}<button data-p1="syncVoice">Use voiceover as spoken script</button></section><section>${textarea('onScreenText','On-screen text',4)}${textarea('captionText','Caption transcript / notes',4)}${textarea('prompt','Full editable video-generation prompt',10)}</section></div><details><summary>Editable scene breakdown · ${P.draft.scenes?.length||0} scenes</summary><p>Each scene includes dialogue/voiceover, captions, shot direction, editing and practice timing. Changes remain editable.</p><textarea id="p1Scenes" rows="16">${h(JSON.stringify(P.draft.scenes,null,2))}</textarea><button data-p1="syncScenes">Build a simple scene from current script</button></details><div class="p1-meta">${input('name','Optional version name')}${input('note','Optional change note')}</div><div class="actions"><button data-p1="saveDraft">Save Draft</button><button class="primary" data-p1="saveVersion">Save as New Version</button><button data-p1="duplicate">Duplicate Version</button><button data-p1="review">Run Script Review</button><button data-p1="approveScript">Approve Script</button></div><details><summary>Initial draft and AI assistance</summary><p>Choose a calendar script as your initial draft, write manually, or request a new draft from Kie. AI requests use provider credits and are never submitted automatically.</p><button data-p1="starter">Create editable starter from brief</button><button data-p1="aiDraft">Generate Initial Script with AI · uses credits</button><button data-p1="aiReview">AI Script Review · uses credits</button></details><section class="panel"><h3>Strategic reasoning</h3><p>${h(P.content.retentionLogic||P.content.evidence||'Editorial hypothesis: solve one real speaking situation, model a sentence, then invite spoken practice.')}</p><p>${h(P.content.experiment?.weakness||'Validate clarity, practical relevance and pronunciation with a real learner; editorial scores do not guarantee reach.')}</p></section>`;}
 function reviewView(){const v=P.history.versions.find(x=>x.id===P.selected),review=v?.approval?.review;return `<div class="actions"><button data-p1="review">Run Script Review</button><button data-p1="aiReview">AI Script Review · uses credits</button><button data-p1="approveScript">Approve Script</button></div>${review?`<section class="panel"><span class="tag">Script Quality Score</span><h2>${review.score}/100</h2><p>${h(review.method)}</p><p>${h(review.approvalRecommendation)}</p><div class="p1-meta">${review.categories.map(c=>`<section><h3>${h(c.name)} · ${c.passed}/${c.total}</h3>${c.improvements.map(s=>`<p>${h(s)}</p>`).join('')||'<p>Structural checks passed; verify meaning manually.</p>'}</section>`).join('')}</div><h3>Generation readiness blockers</h3>${review.blockingIssues.map(s=>`<p>${h(s)}</p>`).join('')||'<p>None found by this check.</p>'}<h3>Human review</h3>${review.manualChecks.map(s=>`<p>${h(s)}</p>`).join('')}<details><summary>Suggested improved version</summary><pre>${h(review.improvedVersion.script)}</pre><button data-p1="applyImprovement">Use as editable draft</button></details>${review.aiReview?`<h3>AI editorial review</h3>${objectCard(review.aiReview)}<button data-p1="applyAIImprovement">Use AI improvement as editable draft</button>`:''}</section>`:empty('No saved quality review','Save a script version, then run the review. Scores and suggestions do not lock your text.')}<section class="panel"><h3>Script comments</h3><textarea id="p1Comment" placeholder="Record a change request or approval note"></textarea><button data-p1="comment">Save Review Comment</button>${(v?.approval?.comments||[]).map(c=>`<p>${h(c.text)}<small>${h(c.actor)} · ${stamp(c.at)}</small></p>`).join('')}${v?.approval?.script?`<p class="badge approved">Approved by ${h(v.approval.script.actor)} · ${stamp(v.approval.script.at)}</p>`:''}</section>`;}
 function diffText(a,b){const x=String(a||'').split(/(\s+)/),y=String(b||'').split(/(\s+)/);if(x.length*y.length>1000000)return `<del>${h(a)}</del><ins>${h(b)}</ins>`;const rows=Array.from({length:x.length+1},()=>new Uint16Array(y.length+1));for(let i=x.length-1;i>=0;i--)for(let j=y.length-1;j>=0;j--)rows[i][j]=x[i]===y[j]?rows[i+1][j+1]+1:Math.max(rows[i+1][j],rows[i][j+1]);let i=0,j=0,out='';while(i<x.length||j<y.length){if(i<x.length&&j<y.length&&x[i]===y[j]){out+=h(x[i++]);j++;}else if(j<y.length&&(i===x.length||rows[i][j+1]>=rows[i+1][j]))out+='<ins>'+h(y[j++])+'</ins>';else out+='<del>'+h(x[i++])+'</del>';}return out;}
 function versionsView(){const options=P.history.versions.map(v=>`<option value="${v.id}">${h(versionLabel(v))}</option>`).join('');return `<section class="panel"><h3>Compare script versions</h3><div class="toolbar"><label>Earlier version<select id="p1CompareA">${options}</select></label><label>Later version<select id="p1CompareB">${options}</select></label><button data-p1="compare">Compare Versions</button></div><div id="p1Diff"></div></section>${P.history.versions.map(v=>`<section class="panel"><div class="row"><h3>${h(versionLabel(v))}</h3><span class="badge ${v.status==='Script approved'?'approved':''}">${h(v.status)}</span></div><p>${h(v.body.note||'')}</p><small>${h(v.actor)} · ${stamp(v.created_at)} · ${P.history.jobs.filter(j=>j.version_id===v.id).length} video attempts</small><div class="actions"><button data-p1-load="${v.id}">Open / Edit Script</button><button data-p1-restore="${v.id}">Restore Version as New</button><button data-p1-generate-version="${v.id}">Generate from this version</button></div></section>`).join('')||empty('No saved versions','Save your first script version. Every future save stays in history.')}`;}
 function generationView(){const ready=P.readiness?.connections,budget=P.readiness?.budget;return `<div class="split"><section class="panel"><h3>Pre-generation readiness</h3>${(ready?.checks||[]).map(c=>`<div class="list-row"><span>${h(c.name)}</span><span class="badge ${c.ready?'approved':''}">${c.ready?'Ready':'Needed'}</span></div>`).join('')}<p>${budget?.usedToday??0}/${budget?.maxJobsPerDay??1} daily video attempts · up to ${budget?.maxSeconds??15} planned seconds · IST.</p><label>Saved Sia reference<select id="p1SiaReference">${SIA_REFERENCES.filter(a=>a.single).map(a=>`<option value="${a.id}">${h(a.title)}</option>`).join('')}</select></label><button data-p1="reference">Use Saved Reference</button><label>Upload a prepared scene frame<input type="file" id="p1ReferenceUpload" accept="image/png,image/jpeg,image/webp"></label>${P.draft.referenceKey?`<img class="reference-preview" src="${media(P.draft.referenceKey)}" alt="Selected Sia reference"><label><input type="checkbox" data-p1-check="referenceApproved" ${P.draft.referenceApproved?'checked':''}> I reviewed this single-person Sia frame</label>`:''}<label><input type="checkbox" data-p1-check="rightsConfirmed" ${P.draft.rightsConfirmed?'checked':''}> Commercial rights confirmed for Sia, voice and assets</label><p class="subtle">The selected frame determines the setting. For a different background, upload a prepared Sia scene. Generated clips use the exact saved prompt and transcript.</p><div class="actions"><button data-p1="saveVersion">Save as New Version</button><button class="primary" data-p1="generate">Generate New Video Version · uses credits</button></div><p class="subtle">Save edits before generating. Repeated status checks reuse the existing task; a new video version is a separate paid request. Keep the workspace open while processing.</p></section><section class="panel"><h3>Video versions</h3>${jobsView()}</section></div>`;}
 function jobsView(){return P.history.jobs.map(j=>{const v=P.history.versions.find(v=>v.id===j.version_id);return `<article class="p1-job" data-job-card="${j.id}"><h3 data-job-status>${videoLabel(j)} · ${h(j.status)}</h3><small>From ${h(v?versionLabel(v):j.version_id)} · ${stamp(j.created_at)}</small><p data-job-stage>${h(j.stage)} ${j.body.clips?.length?'· clip '+((j.body.clipIndex||0)+1)+'/'+j.body.clips.length:''}</p>${j.body.error?`<p class="p1-warning">${h(j.body.error)}</p>`:''}${j.body.audioKey?`<audio controls src="${media(j.body.audioKey)}"></audio>`:''}${j.body.mediaKey?`<video controls playsinline preload="metadata" src="${media(j.body.mediaKey)}"></video>`:''}<details><summary>Exact prompt, transcript and provider history</summary><pre>${h(j.body.prompt||v?.body.prompt)}</pre><p>${h(j.body.script||v?.body.script)}</p><pre>${h(JSON.stringify(j.body.timeline||[],null,2))}</pre><p>Provider task: ${h(j.provider_id||'Not submitted')}</p></details><div class="actions">${['Queued','Generating','Processing'].includes(j.status)?`<button data-p1-resume="${j.id}">Resume / Check Status</button>`:''}${j.provider_id&&['Held','Failed'].includes(j.status)?`<button data-p1-provider-check="${j.id}">Check Provider Failure · no new generation</button>`:''}${['Held','Failed'].includes(j.status)?`<button data-p1-reconcile="${j.id}">Reconcile Existing Job</button>`:''}${j.status==='Completed'?`<button class="primary" data-p1-finish="${j.id}">Captions & Final Video</button>`:''}</div></article>`;}).join('')||empty('No video versions','Save a script and generate the first take.');}
 function finishingView(){const j=P.history.jobs.find(j=>j.id===P.finishing);if(!j)return `<section class="panel"><h3>Choose a completed video</h3>${jobsView()}</section>`;const saved=P.renderDrafts[j.id];const cues=saved?.captions||j.body.captions||[];return `<section class="panel"><h3>Finish ${videoLabel(j)}</h3><p>From ${h(versionLabel(P.history.versions.find(v=>v.id===j.version_id)))}. Review the voice and every source clip before rendering.</p><div class="p1-video-grid">${(j.body.clips||[{mediaKey:j.body.mediaKey}]).map((c,i)=>`<div><video controls playsinline src="${media(c.mediaKey)}"></video><small>Clip ${i+1}</small></div>`).join('')}</div><label>Timed captions · start/end in seconds, text editable<textarea id="p1Captions" rows="12">${h(JSON.stringify(cues,null,2))}</textarea></label><p class="subtle">Native Cartesia timestamps follow the generated voice. Review spelling and timing; keep each cue to one or two short lines.</p><div class="toolbar"><label>Framing<select id="p1Fit"><option value="cover" ${saved?.settings?.fit!=='contain'?'selected':''}>Fill 9:16 · centre crop</option><option value="contain" ${saved?.settings?.fit==='contain'?'selected':''}>Fit whole scene · dark background</option></select></label><label>Horizontal focus<input id="p1Focus" type="range" min="0" max="1" step="0.05" value="${saved?.settings?.focusX??0.5}"></label><label><input id="p1Logo" type="checkbox" ${saved?.settings?.logo!==false?'checked':''}> SpeakX logo after first 2 seconds</label></div><div class="actions"><button data-p1="saveDraft">Save Caption Draft</button><button class="primary" data-p1="renderFinal">Render Captioned Final Video</button><button data-p1="cancelRender" disabled id="p1CancelRender">Cancel Render</button></div><progress id="p1RenderProgress" value="0" max="1"></progress><p id="p1RenderStatus">Rendering runs in real time. Keep this tab visible. ${SiaFinishing.supportedMime()?.startsWith('video/mp4')?'This browser supports MP4 recording.':'This browser may export WebM; the extension will reflect the actual format.'}</p></section><details class="panel"><summary>Upload a finished edit instead</summary><p>You can finish the same source take in your editor and upload the final vertical video. It is saved as a separate immutable export linked to this script and video.</p><input id="p1FinishedUpload" type="file" accept="video/mp4,video/webm"><label><input id="p1UploadedAudio" type="checkbox"> I played the file and confirmed audible Sia speech</label><button data-p1="uploadFinal">Save Finished Video</button></details>`;}
 function finalReviewView(){const exports=P.history.exports;return `<section class="panel"><h3>Compare final video versions</h3><p>Play the versions side by side. Every export below retains its source script, generation attempt, captions and approval.</p><div class="toolbar"><label>Video A<select id="p1VideoA">${exports.map(x=>`<option value="${x.id}">${h(x.id.slice(0,8))} · ${stamp(x.body.createdAt)}</option>`).join('')}</select></label><label>Video B<select id="p1VideoB">${exports.map((x,i)=>`<option value="${x.id}" ${i===1?'selected':''}>${h(x.id.slice(0,8))} · ${stamp(x.body.createdAt)}</option>`).join('')}</select></label><button data-p1="compareVideos">Compare Selected Videos</button></div><div class="p1-video-grid" id="p1VideoComparison">${exports.slice(0,2).map(x=>`<div><video controls playsinline src="${media(x.body.mediaKey)}"></video><small>${h(x.body.notes)} · ${h(x.id.slice(0,8))}</small></div>`).join('')}</div></section>${exports.map((x,i)=>{const v=P.history.versions.find(v=>v.id===x.body.scriptVersionId);return `<section class="panel"><div class="row"><h3>Final Video ${exports.length-i}</h3><span class="badge ${x.body.approval?'approved':''}">${h(x.body.status)}</span></div><p>Source: ${h(v?versionLabel(v):x.body.scriptVersionId)} · ${h(x.body.jobId.slice(0,8))} · ${stamp(x.body.createdAt)}</p><video class="p1-final-player" controls playsinline src="${media(x.body.mediaKey)}"></video><p>${x.body.width}×${x.body.height} · ${Number(x.body.duration).toFixed(1)}s · ${h(x.body.mime)}</p><details><summary>Saved captions and fingerprint</summary><pre>${h(JSON.stringify(x.body.captions,null,2))}</pre><small>${h(x.body.sha256)}</small></details><div class="p1-qa" data-export-qa="${x.id}">${QA.map(k=>`<label><input type="checkbox" data-qa-field="${k}" ${x.body.approval?.qa?.[k]?'checked':''}> ${h(k.replace(/([A-Z])/g,' $1'))}</label>`).join('')}</div><textarea data-export-comment="${x.id}" placeholder="Review comments / changes requested"></textarea><div class="actions"><button data-export-review="${x.id}">Save Video Review</button>${x.body.approval?`<a class="primary p1-download" href="/api/phase1/exports/${x.id}/download" download>Download Approved Video</a>`:`<button class="primary" data-export-approve="${x.id}">Approve Final Version</button>`}</div>${x.body.reviews.map(r=>`<p>${h(r.comment)}<small>${h(r.actor)} · ${stamp(r.at)}</small></p>`).join('')}${x.body.approval?`<p>Approved by ${h(x.body.approval.actor)} · ${stamp(x.body.approval.at)}</p>`:''}</section>`;}).join('')||empty('No finished video yet','Generate a take, then use Captions & Final Video or upload a finished edit.')}`;}
 function historyView(){return `<div class="actions"><button data-p1="exportHistory">Download Complete History</button></div>${P.history.events.map(e=>`<div class="list-row"><b>${h(e.action)}</b><span>${h(e.actor)}</span><small>${stamp(e.at)}</small></div>`).join('')||empty('History starts with the first save','Scripts, prompts, jobs, reviews, approvals and downloads will appear here.')}`;}
 function show(){const dialog=q('#detail');const selected=P.history.versions.find(v=>v.id===P.selected);const tabs=['Script','Review','Versions','Generate','Finish','Final Review','History'];dialog.innerHTML=`<div class="dialog-head"><div><small>${h(P.draft.lessonId)} · Phase 1</small><h2>${h(P.draft.title||'Script Workspace')}</h2><small>${selected?h(versionLabel(selected))+' · '+h(selected.status):'Unsaved initial draft'} · ${selected?h(selected.actor)+' · '+stamp(selected.created_at):'Editable before generation'}</small></div><button id="p1Close">Close</button></div><div class="dialog-body p1-workspace"><div class="tabs">${tabs.map(t=>`<button data-p1-tab="${t}" class="${P.tab===t?'selected':''}">${t}</button>`).join('')}</div><p id="p1Message" class="p1-message" role="status">${h(P.message)}</p><small id="p1SaveStatus">${P.dirty?'Unsaved edits':'Draft / selected version loaded'}</small>${({Script:scriptView,Review:reviewView,Versions:versionsView,Generate:generationView,Finish:finishingView,'Final Review':finalReviewView,History:historyView})[P.tab]()}</div>`;bind();if(!dialog.open)dialog.showModal();}
 function bind(){
  q('#p1Close').onclick=()=>action(async()=>{if(P.controller)throw Error('Finish or cancel rendering before closing.');if(P.dirty){capture();await saveDraft();}q('#detail').close();render();});q('#detail').oncancel=e=>{e.preventDefault();q('#p1Close').click();};
  document.querySelectorAll('[data-p1-field],[data-p1-check],#p1Scenes,#p1Captions,#p1Fit,#p1Focus,#p1Logo').forEach(el=>el.oninput=()=>{changed();});
  document.querySelectorAll('[data-p1-tab]').forEach(b=>b.onclick=()=>action(async()=>{if(P.controller)throw Error('Finish or cancel rendering before changing tabs.');capture();if(P.dirty)await saveDraft();P.tab=b.dataset.p1Tab;P.message='';show();}));
  document.querySelectorAll('[data-p1]').forEach(b=>b.onclick=()=>action(async()=>{b.disabled=true;try{capture();await commands[b.dataset.p1]();}finally{b.disabled=false;}}));
  document.querySelectorAll('[data-p1-load]').forEach(b=>b.onclick=()=>action(async()=>{if(P.dirty)await saveDraft();const v=P.history.versions.find(v=>v.id===b.dataset.p1Load);P.draft=structuredClone(v.body);P.selected=v.id;P.tab='Script';changed();await saveDraft();show();}));
  document.querySelectorAll('[data-p1-restore]').forEach(b=>b.onclick=()=>action(async()=>{if(P.dirty)await saveDraft();const v=await api1('versions/'+b.dataset.p1Restore+'/restore','POST',{});P.selected=v.id;P.draft=structuredClone(v.body);changed();await loadHistory();await saveDraft();P.tab='Script';show();}));
  document.querySelectorAll('[data-p1-generate-version]').forEach(b=>b.onclick=()=>action(async()=>{if(P.dirty)await saveDraft();const v=P.history.versions.find(v=>v.id===b.dataset.p1GenerateVersion);P.selected=v.id;P.draft=structuredClone(v.body);changed();await saveDraft();P.tab='Generate';show();}));
  document.querySelectorAll('[data-p1-provider-check]').forEach(b=>b.onclick=()=>action(async()=>{const j=await api1('jobs/'+b.dataset.p1ProviderCheck+'/provider-status','POST',{});await loadHistory();P.message=j.body.error||'Provider status checked.';show();}));
  document.querySelectorAll('[data-p1-resume]').forEach(b=>b.onclick=()=>run(b.dataset.p1Resume));
  document.querySelectorAll('[data-p1-finish]').forEach(b=>b.onclick=()=>action(async()=>{P.finishing=b.dataset.p1Finish;P.captionDraft=null;P.tab='Finish';show();}));
  document.querySelectorAll('[data-p1-reconcile]').forEach(b=>b.onclick=()=>action(async()=>{const note=prompt('What did you verify in the provider dashboard?');if(!note)return;const taskId=prompt('Verified Kie task ID, if available. Leave blank to check the saved task.');if(taskId===null)return;const j=P.history.jobs.find(j=>j.id===b.dataset.p1Reconcile);const confirmedNoSubmission=!taskId&&!['poll','split'].includes(j.stage)?confirm('Confirm you verified there is NO accepted paid request for this stage. Resuming may use provider credits.'):false;await api1('jobs/'+j.id+'/reconcile','POST',{note,taskId:taskId||undefined,confirmedNoSubmission});await loadHistory();show();await run(j.id);}));
  if(q('#p1ReferenceUpload'))q('#p1ReferenceUpload').onchange=()=>action(async()=>{const file=q('#p1ReferenceUpload').files[0];if(file)await uploadReference(file);});
  document.querySelectorAll('[data-export-review],[data-export-approve]').forEach(b=>b.onclick=()=>action(async()=>{const id=b.dataset.exportReview||b.dataset.exportApprove,x=P.history.exports.find(x=>x.id===id),qa=Object.fromEntries([...document.querySelectorAll(`[data-export-qa="${id}"] [data-qa-field]`)].map(el=>[el.dataset.qaField,el.checked])),comment=document.querySelector(`[data-export-comment="${id}"]`).value;await api1('exports/'+id+(b.dataset.exportApprove?'/approve':'/review'),'POST',{qa,comment,sha256:x.body.sha256});await loadHistory();P.message=b.dataset.exportApprove?'Approved and Ready to Download':'Review saved';show();}));
 }
 async function uploadReference(file){capture();if(file.size>5*1024*1024)throw Error('Choose a Sia frame under 5 MB.');const r=await fetch('/api/reference',{method:'POST',headers:{'Content-Type':file.type||'image/png'},body:file}),data=await r.json();if(!r.ok)throw Error(data.error);P.draft.referenceKey=data.key;P.draft.referenceApproved=false;changed();await saveDraft();show();}
 async function selectedVersion(){capture();const v=P.history.versions.find(v=>v.id===P.selected);if(!v)throw Error('Save a script version first.');const clean=o=>{const c={...o};delete c.parentId;delete c.name;delete c.note;delete c.pendingGeneration;return JSON.stringify(c);};if(clean(v.body)!==clean(P.draft))throw Error('Save your edited script as a new version first.');return v;}
 async function review(ai=false){const v=await selectedVersion();await api1('versions/'+v.id+'/review','POST',{useAI:ai,requestId:crypto.randomUUID()});await loadHistory();P.tab='Review';P.message='Review saved. All text remains editable.';show();}
 async function run(id){if(P.runners.has(id))return;P.runners.add(id);try{for(let n=0;n<150;n++){let j=P.history.jobs.find(j=>j.id===id);if(j&&['Completed','Held','Failed'].includes(j.status))break;if(n&&j?.stage==='poll')await new Promise(r=>setTimeout(r,10000));j=await api1('jobs/'+id+'/advance','POST',{});const ix=P.history.jobs.findIndex(x=>x.id===id);if(ix>=0)P.history.jobs[ix]=j;else P.history.jobs.unshift(j);const card=document.querySelector(`[data-job-card="${j.id}"]`);if(card){card.querySelector('[data-job-status]').textContent=videoLabel(j)+' · '+j.status;card.querySelector('[data-job-stage]').textContent=j.stage+(j.body.clips?.length?' · clip '+((j.body.clipIndex||0)+1)+'/'+j.body.clips.length:'');}notify(videoLabel(j)+': '+j.status+' · '+j.stage+(j.body.error?' — '+j.body.error:''));if(['Completed','Held','Failed'].includes(j.status)){await loadHistory();if(q('#detail').open&&P.tab==='Generate')show();break;}}}catch(e){notify(e.message+' Resume the same job to check its saved state.');}finally{P.runners.delete(id);}}
 async function saveFinal(job,result){const form=new FormData();form.set('file',result.blob,'sia-final.'+(result.blob.type.startsWith('video/mp4')?'mp4':'webm'));form.set('metadata',JSON.stringify(result.metadata));const response=await fetch('/api/phase1/jobs/'+job.id+'/exports',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw Error(data.error);await loadHistory();P.tab='Final Review';P.message='Finished video saved. Watch it and complete the review before approval.';show();}
 const commands={
  compareVideos:async()=>{q('#p1VideoComparison').innerHTML=[q('#p1VideoA').value,q('#p1VideoB').value].map(id=>{const x=P.history.exports.find(x=>x.id===id);return x?`<div><video controls playsinline src="${media(x.body.mediaKey)}"></video><p>${h(x.id.slice(0,8))} · ${h(versionLabel(P.history.versions.find(v=>v.id===x.body.scriptVersionId)))}</p></div>`:'';}).join('');},
  saveDraft,saveVersion,duplicate:async()=>{capture();P.draft.name='Copy of '+(P.draft.name||'script');P.draft.note='Duplicated as an editable new version';show();await saveVersion();},
  syncVoice:async()=>{P.draft.script=P.draft.voiceover;P.draft.captionText=P.draft.script;changed();show();},
  syncScenes:async()=>{P.draft.voiceover=P.draft.script;P.draft.scenes=[{startSeconds:0,endSeconds:P.draft.duration,voiceover:P.draft.script,captionText:P.draft.script,shot:'Only Sia, same approved face and outfit, direct to camera.',edit:'Captions aligned to generated voice.',pauseSeconds:2}];changed();show();},
  starter:async()=>{capture();const phrase=P.content.target||P.draft.keyword;if(!phrase)throw Error('Add the target sentence or keyword in the brief first.');P.draft.script=(P.draft.hook?P.draft.hook+' ':'')+'Try this: '+phrase+'. Ab aapki baari. '+phrase+'. '+(P.draft.cta||'Say it once.');P.draft.voiceover=P.draft.script;P.draft.captionText=P.draft.script;P.draft.name='Editable starter';P.draft.note='Template-assisted starter; review English and meaning before production';await commands.syncScenes();notify('Editable starter created. Review the example carefully before saving.');},
  aiDraft:async()=>{capture();if(!confirm('Generate a new script through Kie? This uses provider credits. Your current draft will be saved first.'))return;await saveDraft();const result=await api1('assist','POST',{kind:'draft',draft:P.draft,requestId:crypto.randomUUID()});for(const key of ['title','hook','script','voiceover','dialogue','cta','prompt','scenes'])if(result[key]!==undefined)P.draft[key]=result[key];P.draft.prompt=withSiaReferencePolicy(P.draft.prompt);P.draft.name='Initial AI Draft';P.draft.note='Kie AI draft; editable and awaiting review';changed();await saveDraft();show();},
  review:()=>review(false),aiReview:async()=>{if(confirm('Request an AI script review through Kie? This uses provider credits.'))await review(true);},
  applyImprovement:async()=>{const v=P.history.versions.find(v=>v.id===P.selected);P.draft={...P.draft,...v.approval.review.improvedVersion,name:'Review improvement'};P.tab='Script';changed();show();},
  applyAIImprovement:async()=>{const v=P.history.versions.find(v=>v.id===P.selected),r=v.approval.review.aiReview.improvedVersion;for(const k of ['script','hook','cta','prompt','scenes'])if(r?.[k]!==undefined)P.draft[k]=r[k];P.draft.voiceover=P.draft.script;P.draft.name='AI review improvement';P.tab='Script';changed();show();},
  approveScript:async()=>{const v=await selectedVersion();await api1('versions/'+v.id+'/approve-script','POST',{comment:q('#p1Comment')?.value||''});await loadHistory();P.message='This exact script version is approved. Further edits create a new version.';show();},
  comment:async()=>{const v=await selectedVersion();await api1('versions/'+v.id+'/comment','POST',{comment:q('#p1Comment').value});await loadHistory();show();},
  compare:async()=>{const a=P.history.versions.find(x=>x.id===q('#p1CompareA').value),b=P.history.versions.find(x=>x.id===q('#p1CompareB').value);if(!a||!b)return;const keys=[...fields.map(x=>x[0]),'script','voiceover','dialogue','onScreenText','captionText','prompt','scenes'];q('#p1Diff').innerHTML=`<div class="split"><section><h3>${h(versionLabel(a))}</h3><pre>${h(a.body.script)}</pre></section><section><h3>${h(versionLabel(b))}</h3><pre>${h(b.body.script)}</pre></section></div><h3>Additions and removals</h3>${keys.filter(k=>JSON.stringify(a.body[k])!==JSON.stringify(b.body[k])).map(k=>`<h4>${h(k)}</h4><div class="p1-diff">${diffText(typeof a.body[k]==='object'?JSON.stringify(a.body[k],null,2):a.body[k],typeof b.body[k]==='object'?JSON.stringify(b.body[k],null,2):b.body[k])}</div>`).join('')||'<p>These fields are identical.</p>'}`;},
  reference:async()=>{const asset=SIA_REFERENCES.find(a=>a.id===q('#p1SiaReference').value&&a.single);const r=await fetch('/'+asset.file);if(!r.ok)throw Error('Reference image unavailable.');await uploadReference(await r.blob());},
  generate:async()=>{const v=await selectedVersion();if(!confirm('Generate a new video from '+versionLabel(v)+'? Cartesia and Kie provider credits will be used.'))return;let requestId=P.pending.get(v.id)||(P.draft.pendingGeneration?.versionId===v.id?P.draft.pendingGeneration.requestId:null);if(!requestId){requestId=crypto.randomUUID();P.pending.set(v.id,requestId);P.draft.pendingGeneration={versionId:v.id,requestId};await saveDraft();}await api1('versions/'+v.id+'/review','POST',{});const j=await api1('jobs','POST',{versionId:v.id,requestId});P.pending.delete(v.id);delete P.draft.pendingGeneration;await saveDraft();await loadHistory();P.readiness=await api1('readiness');P.tab='Generate';show();await run(j.id);},
  renderFinal:async()=>{const job=P.history.jobs.find(j=>j.id===P.finishing);let captions;try{captions=JSON.parse(q('#p1Captions').value);}catch{throw Error('Caption cues must be valid JSON.');}P.renderDrafts[job.id]={captions,settings:{fit:q('#p1Fit').value,focusX:Number(q('#p1Focus').value),logo:q('#p1Logo').checked}};await saveDraft();P.controller=new AbortController();q('#p1CancelRender').disabled=false;try{const result=await SiaFinishing.render({job,captions,settings:{fit:q('#p1Fit').value,focusX:Number(q('#p1Focus').value),logo:q('#p1Logo').checked},signal:P.controller.signal,onProgress:p=>{q('#p1RenderProgress').value=p.fraction;q('#p1RenderStatus').textContent='Rendering '+p.seconds.toFixed(1)+' / '+p.duration.toFixed(1)+' seconds';}});P.controller=null;await saveFinal(job,result);}finally{P.controller=null;if(q('#p1CancelRender'))q('#p1CancelRender').disabled=true;}},
  cancelRender:async()=>P.controller?.abort(),
  uploadFinal:async()=>{const job=P.history.jobs.find(j=>j.id===P.finishing),file=q('#p1FinishedUpload').files[0];if(!file)throw Error('Choose the finished MP4 or WebM.');if(!q('#p1UploadedAudio').checked)throw Error('Play the file and confirm audible Sia speech.');const url=URL.createObjectURL(file),video=document.createElement('video');try{await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Video took too long to decode.')),20000);video.onloadedmetadata=()=>{clearTimeout(timeout);resolve();};video.onerror=()=>{clearTimeout(timeout);reject(Error('Video cannot be decoded.'));};video.src=url;});await saveFinal(job,{blob:file,metadata:{duration:video.duration,width:video.videoWidth,height:video.videoHeight,captions:JSON.parse(q('#p1Captions').value),audioPresent:true,notes:'Externally finished edit of this source video; human review required.'}});}finally{URL.revokeObjectURL(url);}},
  exportHistory:async()=>download(P.draft.lessonId+'-complete-history.json',JSON.stringify({idea:P.content,...P.history},null,2),'application/json'),
 };
 function studio(){return heading('Create. Review. Download.','Phase 1 · Only Sia · Manual publishing',`<button data-go="backlog">Create Content Idea</button>`)+`<section class="panel"><p>Each idea has an editable script workspace, immutable script and video versions, caption finishing and final approval. Approved videos are downloaded for your team to publish manually.</p></section><div class="cards">${[...P.ideas.map(x=>x.body),...all()].map(e=>`<section class="panel"><span class="tag">${h(e.date||'Custom idea')}</span><h3>${h(e.topic||e.title)}</h3><p>${h(e.hook||e.evidence||'Create the script from this brief.')}</p><small>${h(e.persona||e.audience||'SpeakX learner')}</small><div class="actions"><button class="primary" data-open="${e.id||e.contentId}">Open Script Workspace</button></div></section>`).join('')}</div>`;}
 function ideas(){return heading('Start with a speaking problem.','Content idea → dedicated Script Workspace')+`<section class="panel"><div class="p1-meta"><label>Working title<input id="p1IdeaTitle"></label><label>Target audience<input id="p1IdeaAudience" value="Indian adults learning spoken English"></label><label>Target sentence / learning point<input id="p1IdeaTarget"></label></div><label>Strategic reasoning / evidence<textarea id="p1IdeaEvidence" placeholder="Learner question, source or clearly labelled hypothesis"></textarea></label><button class="primary" id="p1CreateIdea">Create Idea & Script Workspace</button></section>${P.ideas.map(x=>`<section class="panel"><h3>${h(x.body.title)}</h3><p>${h(x.body.evidence)}</p><button data-open="${x.body.contentId}">Open Script Workspace</button></section>`).join('')}<section class="panel"><h3>Existing idea backlog</h3>${(state.ideas||[]).map(i=>`<p>${h(i.title)} · ${h(i.evidence)}</p>`).join('')||'<p>Calendar ideas remain available in the 30-day plan.</p>'}</section>`;}
 function downloads(){const ready=P.exports.filter(x=>x.body.status==='Approved and Ready to Download');return heading('Approved and Ready to Download','Your team publishes manually')+`<section class="panel"><p>Only approved finished files appear here. No social publishing connection is required for Phase 1.</p></section>${ready.map(x=>`<section class="panel"><h3>${h(x.body.lessonId)}</h3><video class="p1-final-player" controls playsinline src="${media(x.body.mediaKey)}"></video><p>${stamp(x.body.approval.at)} · ${h(x.body.approval.actor)}</p><a class="primary p1-download" href="/api/phase1/exports/${x.id}/download" download>Download Approved Video</a><button data-open="${x.body.lessonId}">Open Complete History</button></section>`).join('')||empty('No approved final videos yet','Generate → finish captions → review the actual video → approve.')}<section class="panel"><h3>Manual publishing checklist</h3>${['Play the downloaded file and verify its first and last words.','Use the approved platform caption, cover and CTA.','Upload manually to the intended SpeakX account.','Preview caption safe zones and check audio before posting.','Record the live post link and publication time for reporting.'].map(x=>`<p>□ ${h(x)}</p>`).join('')}</section>`;}
 function approvals(){return heading('Review the exact video.','Script approval and final media approval are separate')+`<section class="panel">${P.exports.filter(x=>!x.body.approval).map(x=>`<div class="list-row"><span>${h(x.body.lessonId)} · ${h(x.body.status)}</span><button data-open="${x.body.lessonId}">Open Workspace to Review</button></div>`).join('')||empty('No finished exports awaiting review','Finish a generated video first. Script reviews are available inside each workspace.')}</section>`;}
 function settings(){if(session?.user.role!=='Owner')return '';const b=P.readiness?.budget||{};return `<section class="panel"><h2>Phase 1 generation limits</h2><p>Limits apply to new video versions per IST day. Multiple short provider clips may be needed for one lesson. This is a usage limit, not a currency quote.</p><div class="p1-meta"><label>Maximum video versions per day<input id="p1DailyLimit" type="number" min="1" max="20" value="${b.maxJobsPerDay||1}"></label><label>Maximum lesson duration (seconds)<input id="p1DurationLimit" type="number" min="5" max="120" value="${b.maxSeconds||15}"></label><label>Maximum AI script/review requests per day<input id="p1AssistLimit" type="number" min="1" max="20" value="${b.maxAssistPerDay||5}"></label></div><button id="p1SaveBudget">Save Phase 1 Limits</button><p>${b.usedToday||0} video versions requested today. Provider generation also needs to be enabled above.</p></section>`;}
 function bindPage(){if(q('#p1CreateIdea'))q('#p1CreateIdea').onclick=()=>action(async()=>{const idea=await api1('ideas','POST',{title:q('#p1IdeaTitle').value,audience:q('#p1IdeaAudience').value,target:q('#p1IdeaTarget').value,evidence:q('#p1IdeaEvidence').value});P.ideas.unshift(idea);await open(idea.body.contentId);});if(q('#p1SaveBudget'))q('#p1SaveBudget').onclick=()=>action(async()=>{await api1('budget','PUT',{maxJobsPerDay:Number(q('#p1DailyLimit').value),maxSeconds:Number(q('#p1DurationLimit').value),maxAssistPerDay:Number(q('#p1AssistLimit').value)});P.readiness=await api1('readiness');render();toast('Phase 1 limits saved.');});}
 async function test(){await open(all()[0].id);const script='Main Sia hoon. Bolo: Could you please repeat the question? Ab aapki baari.';P.draft={...initial(all()[0]),title:'Sia voice and identity test',script,voiceover:script,captionText:script,hook:'Could you please repeat the question?',duration:10,name:'Short Sia test',note:'Voice, identity and lip-sync validation',scenes:[{startSeconds:0,endSeconds:10,voiceover:script,captionText:script,shot:'Sia alone, chest-up, eye-level.',edit:'Simple continuous shot.',pauseSeconds:0}]};P.draft.prompt=withSiaReferencePolicy('Only Sia, same approved reference face, hair and outfit. One continuous shot, subtle gestures, accurate lip sync to the supplied audio. No text, other people or music.');P.selected=null;P.tab='Generate';changed();show();}
 window.addEventListener('beforeunload',e=>{if(P.dirty||P.controller){e.preventDefault();e.returnValue='';}});
 return {bootstrap,open,studio,ideas,downloads,approvals,settings,bindPage,test,diffText,state:P};
})();
