// Shared, deterministic production contract. Never changes a saved script.
export const REEL_FORMAT=Object.freeze({width:1080,height:1920,fps:30,videoCodec:'h264',audioCodec:'aac',channels:2});
export const REEL_LABEL='Output Format: Instagram Reel — 1080 × 1920, 9:16';
const tokens=s=>String(s||'').trim().split(/\s+/).filter(Boolean);
const norm=s=>String(s).toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
export function validateCaptionTranscript(script,cues){return tokens(script).join(' ')===tokens((cues||[]).map(c=>c.text).join(' ')).join(' ');}
export function alignCaptionWords(script,words){
 const source=tokens(script);if(!source.length||!words?.length)throw Error('Script and word timestamps are required.');
 const a=source.map(norm),b=words.map(w=>norm(w.word)),n=a.length,m=b.length;
 const dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=0;i<=n;i++)dp[i][0]=i;for(let j=0;j<=m;j++)dp[0][j]=j;
 for(let i=1;i<=n;i++)for(let j=1;j<=m;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));
 let i=n,j=m;const map=new Array(n);while(i||j){if(i&&j&&dp[i][j]===dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1)){map[--i]=--j;}else if(i&&dp[i][j]===dp[i-1][j]+1)i--;else j--;}
 if(dp[n][m]>Math.max(1,n*.35))throw Error('Voice timestamps differ too much from the selected script. Review the saved voice before finishing.');
 const result=source.map((word,k)=>map[k]===undefined?{word}:{word,start:words[map[k]].start,end:words[map[k]].end});
 for(let k=0;k<n;k++)if(result[k].start===undefined){const from=k;while(k<n&&result[k].start===undefined)k++;const start=from?result[from-1].end:words[0].start,end=k<n?result[k].start:words.at(-1).end;if(end-start<.02*(k-from))throw Error('Missing word timestamps need manual alignment before finishing.');const span=end-start;for(let p=from;p<k;p++)Object.assign(result[p],{start:start+span*(p-from)/(k-from),end:start+span*(p-from+1)/(k-from)});k--;}
 result[0].start=words[0].start;result.at(-1).end=words.at(-1).end;return result;
}
export function toSrt(cues){const stamp=t=>{const ms=Math.round(t*1000);return String(Math.floor(ms/3600000)).padStart(2,'0')+':'+String(Math.floor(ms/60000)%60).padStart(2,'0')+':'+String(Math.floor(ms/1000)%60).padStart(2,'0')+','+String(ms%1000).padStart(3,'0');};return cues.map((c,i)=>`${i+1}\n${stamp(c.start)} --> ${stamp(c.end)}\n${c.text}\n`).join('\n');}
export function validateProduction(script,p){const e=[];if(!p||typeof p!=='object')return ['Prepare the Reel production plan.'];if(!String(p.presenterPrompt||script.prompt||'').trim())e.push('Presenter directions are required.');if(String(p.presenterPrompt||script.prompt||'').length>4800)e.push('Presenter directions must be at most 4800 characters.');if(p.presenterPrompt&&!p.prompt?.includes(p.presenterPrompt))e.push('Rebuild the full production prompt after editing presenter directions.');if(!p.prompt?.includes(script.script))e.push('Production prompt must contain the exact selected full script.');if(p.captionsEnabled!==true)e.push('Full-video captions must be enabled.');for(const [k,v]of Object.entries(REEL_FORMAT))if(p.format?.[k]!==v)e.push('Locked Reel format requires '+k+' = '+v+'.');if(!Array.isArray(p.broll)||p.broll.length<2||p.broll.length>3)e.push('Plan two or three relevant B-roll inserts.');else p.broll.forEach((b,i)=>{if(!Number.isFinite(b.start)||!Number.isFinite(b.end)||b.start<0||b.end-b.start<1.5||b.end-b.start>3||b.end>script.duration||(i&&b.start<p.broll[i-1].end))e.push('B-roll '+(i+1)+' needs non-overlapping 1.5–3 second timing inside the lesson.');for(const k of ['visual','purpose','shot','transition','voiceover','captionTreatment','returnToSia','text'])if(!String(b[k]||'').trim())e.push('B-roll '+(i+1)+' needs '+k+'.');if(tokens(b.text).length>20)e.push('B-roll '+(i+1)+' text must be at most 20 words.');if(b.type!=='teaching-card')e.push('Use the supported teaching-card B-roll type.');});if(Array.isArray(p.broll)&&p.broll.reduce((n,b)=>n+Math.max(0,b.end-b.start),0)>=script.duration/2)e.push('Keep Sia on screen for the majority of the lesson.');if(!Array.isArray(p.highlightTerms)||!p.highlightTerms.length)e.push('Choose an English teaching term to highlight.');return [...new Set(e)];}
export function defaultProduction(v){const b=v.body,script=b.script;const sentences=script.match(/[^.!?]+[.!?]?/g)?.map(s=>s.trim()).filter(Boolean)||[script];const examples=sentences.filter(s=>/\b(my name|i am|could|please|would|can i|thank|introduce)\b/i.test(s));const pool=[...new Set(examples.length?examples:sentences)];const chosen=[pool[0],pool[Math.floor(pool.length/2)],pool.at(-1)];const duration=Number(b.duration);const positions=[.12,.43,.7];const broll=positions.slice(0,duration>=15?3:2).map((p,i)=>{const start=+(duration*p).toFixed(2),end=+(start+Math.min(2.2,duration*.12)).toFixed(2),text=chosen[i%chosen.length];return {start,end,type:'teaching-card',text,visual:'Animated sentence card for the spoken example: '+text,purpose:'Reinforce the sentence being taught and invite the learner to practise.',shot:'Full-screen clean typography on SpeakX pale-blue and charcoal; no additional people.',transition:'150 ms soft dissolve from Sia',voiceover:'Continue the original Sia audio without interruption.',captionTreatment:'Keep exact synchronized speech captions above bottom controls with orange teaching-term highlights.',returnToSia:'150 ms dissolve back to the same Sia take.'};});const production={presenterPrompt:b.prompt,format:{...REEL_FORMAT},captionsEnabled:true,highlightTerms:['name','student','engineer','introduce'],broll,scriptVersionId:v.id,prompt:''};production.prompt=buildProductionPrompt(v,production);return production;}
export function buildProductionPrompt(v,p){const b=v.body;return `${REEL_LABEL}\nProduction source: Script V${b.versionNumber} — ${b.name||'Saved script'} (${v.id}).\nEXACT SPOKEN SCRIPT — do not paraphrase:\n${b.script}\nEND EXACT SCRIPT\n\nSIA SOURCE FOOTAGE: ${p.presenterPrompt||b.prompt}\nThis source direction applies to presenter footage only. The final edit adds the B-roll and captions below. Preserve approved Sia identity, face, hair and outfit. Sia alone, warm expression, small natural gestures, eye-level framing with face fully visible, consistent soft light. Use the selected Cartesia Sia voice, ${b.language}; supplied audio is authoritative.\n\nSCENE PLAN (target timing; align to actual audio):\n${JSON.stringify((b.script.match(/[^.!?]+[.!?]?/g)||[b.script]).map((line,i,all)=>({startSeconds:+(b.duration*i/all.length).toFixed(2),endSeconds:+(b.duration*(i+1)/all.length).toFixed(2),voiceover:line.trim(),shot:'Sia direct to camera; warm expression; small natural gestures.'})),null,2)}\nB-ROLL INSERTS:\n${JSON.stringify(p.broll,null,2)}\nKeep Sia on screen for the majority. Small framing changes every 2–4 seconds. Continuous original Sia voice during every insert; no extra speakers.\nCAPTIONS: every exact spoken word from first to last including CTA, synchronized to voice timestamps. 5–8 words, maximum two lines, bold white on dark translucent background at lower-middle, above bottom 20% and clear of right 12%. Never cover face or mouth. Orange highlight terms: ${p.highlightTerms.join(', ')}. Continue captions through all B-roll and transitions. Save editable SRT.\nCTA: preserve the final spoken line exactly. No additional end card.\nAUDIO: no background music for this pilot; clear centered stereo voice, no cuts or clipping.\nNEGATIVE: No landscape or square output; no black bars; no cropped face; no missing captions; no incorrect subtitle text; no random B-roll; no visual distortion; no extra fingers or malformed hands; no unnatural body movement; no incorrect lip-sync; no change in Sia identity; no abrupt audio cuts; no loud music over speech; no unsupported claims; no unnecessary end screen; no provider watermark where watermark-free generation is supported.\nEXPORT: MP4, H.264, AAC stereo, 1080 × 1920, 9:16 portrait, minimum 30 FPS. Correctly reframe without stretching. Validate actual file tracks before approval.`;}
export function resolveBrollTiming(production,words,duration){
 const all=words.map(w=>norm(w.word));let previousEnd=0;
 return production.broll.map((b,i)=>{const phrase=tokens(b.text).map(norm);let at=-1;for(let k=0;k<=all.length-phrase.length;k++)if(words[k].start>=previousEnd&&phrase.every((t,n)=>t===all[k+n])){at=k;break;}
 const length=Math.min(2.2,Math.max(1.5,b.end-b.start));const latest=duration-((production.broll.length-i)*length)-((production.broll.length-i-1)*.7)-.3;
 const desired=at>=0?words[at].start:duration*[.12,.43,.7][i];const start=Math.max(i?previousEnd+.7:0,Math.min(desired,latest));previousEnd=start+length;return {...b,start:+start.toFixed(3),end:+previousEnd.toFixed(3)};});
}
export function hookSuggestions(b){const interview=/interview/i.test(b.script+' '+b.title);return (interview?['Interview mein introduction atak jaata hai?','Interview introduction: bas naam aur role.','Apna introduction in do lines mein bolo.']:['Is sentence ko confidently bol paoge?','Ek sentence. Aaj hi bolkar dekho.','Yeh English line roz kaam aayegi.']).map((text,i)=>({text,scores:{scrollStop:[8,7,7][i],relevance:9,curiosity:[8,6,7][i],emotion:[8,6,7][i],clarity:[8,9,9][i],expectedRetention:[7,8,8][i]},method:'Creative estimate /10 — not measured performance or a guarantee.'}));}
if(typeof window!=='undefined')window.ReelTools={resolveBrollTiming,REEL_FORMAT,REEL_LABEL,validateProduction,alignCaptionWords,validateCaptionTranscript,toSrt,defaultProduction,buildProductionPrompt,hookSuggestions};
